"""Days 1-45. See scripts/curriculum.py for the row shape."""

DAYS = [
 (1, "how-your-code-actually-runs",
  "How your code actually runs, and where the time goes",
  "You can read a function and point at the one line that does most of the work.",
  "Walk me through this function line by line. Which line runs the most times?",
  "What happens when you type google.com and press Enter",
  "You can narrate the whole journey from keypress to pixels without notes.",
  "What happens when you type google.com into your browser and hit Enter?"),

 (2, "counting-steps",
  "Counting steps: your first cost model",
  "You can count how many times a loop body runs, for any input size, without running the code.",
  "How many times does the inner loop execute if the array has n elements?",
  "Client and server, explained properly",
  "You can draw the client-server picture and say exactly which machine does what.",
  "What is the difference between a client and a server? Where does your code live?"),

 (3, "big-o-in-plain-english",
  "Big-O in plain English",
  "You can say O(n), O(n log n) or O(n^2) about your own code and defend the answer.",
  "What is the time complexity of your solution?",
  "IP addresses, ports, and DNS",
  "You can explain how a name becomes a machine, and what a port is for.",
  "How does the browser find the server for google.com?"),

 (4, "the-growth-curves",
  "The growth curves you will meet again and again",
  "You can rank O(1), O(log n), O(n), O(n log n), O(n^2), O(2^n) and know what input size each survives.",
  "n is 100000. Will an O(n^2) solution pass?",
  "TCP and UDP",
  "You can say why a video call uses one and a bank transfer uses the other.",
  "TCP or UDP for a live video call, and why?"),

 (5, "python-lists-and-tuples",
  "Python for DSA I: lists, tuples, and slicing",
  "You know the real cost of append, pop, insert and a slice, so you stop writing accidental O(n^2).",
  "What is the complexity of inserting at the front of a Python list?",
  "HTTP: the request and the response",
  "You can write out a real HTTP request and response by hand and label every part.",
  "Describe an HTTP request. What is in the headers, and what is in the body?"),

 (6, "python-strings-dicts-sets",
  "Python for DSA II: strings, dictionaries, and sets",
  "You reach for a dict or a set by reflex when a problem asks whether you have seen something before.",
  "How would you check for duplicates in O(n)?",
  "HTTPS and TLS, without the maths",
  "You can explain what the padlock actually guarantees, and what it does not.",
  "What does HTTPS protect you from? What does it not protect you from?"),

 (7, "space-complexity",
  "Space complexity, and what in-place really means",
  "You can state the extra memory your solution uses and rewrite it to use less.",
  "Can you do that in O(1) extra space?",
  "What a web server actually does",
  "You can describe the loop a server runs: listen, accept, handle, respond.",
  "What happens inside the server between receiving a request and sending a response?"),

 (8, "reading-a-problem",
  "Reading a problem like the interviewer wrote it",
  "You can extract input, output, constraints and edge cases from a problem in two minutes.",
  "Before you write code, what questions do you have about the problem?",
  "Processes, threads, and concurrency",
  "You can explain the difference between a process and a thread, and why servers use both.",
  "What is the difference between a process and a thread?"),

 (9, "what-an-array-is",
  "What an array really is in memory",
  "You can explain why arr[500000] is as fast as arr[0], using one picture.",
  "Why is array indexing O(1)?",
  "CPU, RAM, and disk: the speed hierarchy",
  "You can order register, cache, RAM, SSD, disk and network by speed, and say how far apart they are.",
  "How much slower is a disk read than a memory read?"),

 (10, "traversal-patterns",
  "Traversal: the loop patterns you will reuse forever",
  "You can write forward, backward, paired and windowed loops without fighting the indices.",
  "Iterate over every adjacent pair in the array.",
  "Latency numbers every engineer should know",
  "You can quote the handful of numbers that make back-of-the-envelope estimation possible.",
  "Roughly how long is a network round trip to a data centre on another continent?"),

 (11, "insert-and-delete",
  "Insert, delete, and the cost of the middle",
  "You can say why adding to the end is cheap and adding to the middle is not.",
  "What is the cost of deleting an element from the middle of an array?",
  "The operating system's job",
  "You can name what the OS does for your program: memory, scheduling, files, network.",
  "What does the operating system do when your program asks to read a file?"),

 (12, "linear-search",
  "Searching an array: linear search, done properly",
  "You can write a search that handles not-found, duplicates and empty input correctly.",
  "Find the index of a target. What do you return if it is not there?",
  "How your code becomes a running service",
  "You can describe the path from a source file to a process serving live traffic.",
  "How does the code you wrote end up running on a server?"),

 (13, "reverse-and-rotate",
  "Reversing, rotating, and swapping in place",
  "You can rotate an array by k using the three-reversal trick and explain why it works.",
  "Rotate the array to the right by k, in O(1) extra space.",
  "Containers and why everyone uses Docker",
  "You can explain what a container gives you that a virtual machine does not.",
  "What problem does Docker actually solve?"),

 (14, "single-pass-habit",
  "Max, min, second largest: the single-pass habit",
  "You solve find-the-two-largest in one pass instead of reaching for sort.",
  "Find the second largest element without sorting.",
  "Fundamentals revision and interview questions",
  "You can answer the ten most common fundamentals questions cold.",
  "Pick any topic from days 1 to 13 and answer it with no preparation."),

 (15, "the-write-pointer",
  "Moving elements: zeros, duplicates, and the write pointer",
  "You can compact an array in place with a read index and a write index.",
  "Move all zeros to the end while keeping the order of the other elements.",
  "What an API is",
  "You can explain an API to a non-engineer, and then to an engineer.",
  "What is an API? Give me an example of one you have used."),

 (16, "2d-arrays",
  "2D arrays and matrix traversal",
  "You can walk a matrix by row, by column and by diagonal without index confusion.",
  "Print the matrix diagonally.",
  "REST, properly",
  "You can list the REST constraints and say which ones real APIs actually follow.",
  "What makes an API RESTful?"),

 (17, "matrix-tricks",
  "Matrix tricks: rotate, spiral, transpose",
  "You can rotate a matrix ninety degrees in place and print it in spiral order.",
  "Rotate the image ninety degrees clockwise, in place.",
  "Designing a good REST endpoint",
  "You can name a resource, pick the verb, and design a URL the interviewer will not argue with.",
  "Design the endpoints for a comments feature."),

 (18, "arrays-revision",
  "Arrays revision and mock round",
  "You can solve two unseen array problems in forty-five minutes, thinking out loud.",
  "Two array problems, no hints, talk as you go.",
  "Status codes, errors, and idempotency",
  "You can pick the right status code and explain why retrying a POST is dangerous.",
  "Your client retries a failed payment request. What could go wrong?"),

 (19, "what-a-string-is",
  "What a string is, and why it is immutable",
  "You can explain why building a string with += inside a loop is a trap in Python.",
  "Why is string concatenation in a loop slow?",
  "Authentication and authorisation",
  "You can state the difference in one sentence and give a real example of each.",
  "What is the difference between authentication and authorisation?"),

 (20, "building-strings",
  "Building strings without the quadratic trap",
  "You build strings with a list and join, and can show the cost difference with numbers.",
  "Build a string of n characters efficiently.",
  "JWT, sessions, and OAuth",
  "You can explain how a user stays logged in, three different ways, and compare them.",
  "How do you keep a user logged in across requests?"),

 (21, "frequency-maps",
  "Character counting and frequency maps",
  "You reach for a counter dictionary the moment a problem says how many times.",
  "Find the first non-repeating character in a string.",
  "GraphQL versus REST",
  "You can argue for either one, given a real product constraint.",
  "When would you choose GraphQL over REST?"),

 (22, "anagrams",
  "Anagrams: the sorting versus counting choice",
  "You can give two solutions with different complexities and say which one you would ship.",
  "Are these two strings anagrams? Now group a list of words into anagram groups.",
  "gRPC and when binary protocols win",
  "You can say why internal services often do not speak JSON over HTTP.",
  "Why would a company use gRPC between its own services?"),

 (23, "palindromes",
  "Palindromes and the two-ends habit",
  "You can check a palindrome with two pointers and handle the messy input rules.",
  "Is this string a palindrome, ignoring punctuation and case?",
  "Rate limiting and API gateways",
  "You can describe the token bucket and say where the limiter sits in the architecture.",
  "How would you stop one client from hammering your API?"),

 (24, "substrings-vs-subsequences",
  "Substrings versus subsequences: the distinction they test",
  "You never confuse the two again, and you know how many of each a string has.",
  "How many substrings does a string of length n have? How many subsequences?",
  "API revision and interview questions",
  "You can design and defend an API for an unseen feature in fifteen minutes.",
  "Design the API for a food delivery app's order flow."),

 (25, "pattern-matching",
  "Pattern matching, the simple way",
  "You can write naive substring search and state its cost honestly.",
  "Implement strStr: find the first occurrence of a needle in a haystack.",
  "What a database gives you that a file does not",
  "You can list the four things a database does that your own file-handling code would get wrong.",
  "Why not just store the data in a JSON file?"),

 (26, "strings-revision",
  "Strings revision and mock round",
  "You can solve two unseen string problems under time pressure.",
  "Two string problems, no hints, talk as you go.",
  "Tables, rows, and keys",
  "You can design a small schema with primary and foreign keys and justify every column.",
  "Design the tables for a blog with users, posts and comments."),

 (27, "two-pointers-idea",
  "Two pointers: the idea",
  "You can spot the shape of a problem that two pointers turns from O(n^2) into O(n).",
  "Can you do better than the nested loop?",
  "SQL you must know for interviews",
  "You can write SELECT, WHERE, GROUP BY, HAVING and ORDER BY without looking anything up.",
  "Write a query for the top five customers by total spend."),

 (28, "opposite-ends",
  "Opposite ends: pair sums on a sorted array",
  "You can find a pair summing to a target in O(n) and argue that you miss nothing.",
  "Find two numbers in a sorted array that add up to the target.",
  "Joins, drawn",
  "You can draw inner, left, right and full joins and predict the row count of each.",
  "What is the difference between an inner join and a left join?"),

 (29, "read-write-pointer",
  "Same direction: the read pointer and the write pointer",
  "You can remove duplicates from a sorted array in place, in one pass.",
  "Remove duplicates in place and return the new length.",
  "Normalisation and when to break it",
  "You can normalise a schema to third normal form, then argue for denormalising part of it.",
  "When would you deliberately duplicate data across tables?"),

 (30, "fast-and-slow",
  "Fast and slow pointers",
  "You can find the middle of a sequence in one pass and detect a loop in it.",
  "Find the middle element in a single pass.",
  "Indexes: how a database finds a row fast",
  "You can explain why an index makes reads fast and writes slower.",
  "This query is slow. How do you find out why, and what do you do about it?"),

 (31, "fixed-window",
  "Fixed-size sliding window",
  "You can answer every window-of-size-k question in O(n) instead of O(n*k).",
  "Find the maximum sum of any subarray of size k.",
  "B-trees and why indexes are shaped that way",
  "You can draw a B-tree and explain why the database does not use a binary tree on disk.",
  "Why is a database index a B-tree and not a binary search tree?"),

 (32, "variable-window",
  "Variable-size sliding window",
  "You can grow and shrink a window against a condition and never lose track of the invariant.",
  "Find the smallest subarray with a sum at least k.",
  "Query plans and the slow query",
  "You can read an EXPLAIN output and say which part of the query is the problem.",
  "Here is an EXPLAIN plan. What is wrong with this query?"),

 (33, "window-with-a-map",
  "Window plus hash map: the longest-substring family",
  "You can solve longest substring without repeating characters and its five cousins.",
  "Find the length of the longest substring without repeating characters.",
  "Transactions and ACID",
  "You can explain each of the four ACID letters with a bank-transfer example.",
  "What does ACID stand for, and why does it matter?"),

 (34, "at-most-k",
  "At-most-K, and the exactly-K trick",
  "You can turn an exactly-K problem into two at-most-K problems and explain the subtraction.",
  "Count the subarrays with exactly k distinct integers.",
  "Isolation levels and the anomalies they allow",
  "You can name dirty read, non-repeatable read and phantom read, and which level stops each.",
  "What isolation level would you use, and what anomaly are you accepting?"),

 (35, "choosing-the-pattern",
  "Choosing between two pointers and a window, under pressure",
  "You can look at a new problem and pick the right pattern in under a minute.",
  "You have thirty seconds. What pattern does this problem want?",
  "Locking and deadlocks",
  "You can describe how two transactions deadlock and how the database resolves it.",
  "What is a deadlock, and how would you prevent one?"),

 (36, "two-pointers-revision",
  "Two pointers revision and mock round",
  "You can solve two unseen pointer or window problems cold.",
  "Two problems, no hints, talk as you go.",
  "NoSQL: what it actually means",
  "You can stop saying NoSQL is faster and start naming the real trade-off.",
  "What is the difference between SQL and NoSQL?"),

 (37, "prefix-sums",
  "Prefix sums: answering range queries instantly",
  "You can precompute once and then answer any range-sum question in O(1).",
  "Answer many range-sum queries on a fixed array.",
  "Key-value stores",
  "You can say what Redis and DynamoDB are good at, and what they cannot do.",
  "When would you use a key-value store instead of a relational database?"),

 (38, "subarray-sum-k",
  "Subarray sum equals K: prefix plus hash map",
  "You can count subarrays with a given sum in one pass, including the negative-number case.",
  "Count the subarrays whose sum equals k.",
  "Document databases",
  "You can model a domain as documents and say where the model breaks.",
  "Model a blog in MongoDB. What happens when a user changes their name?"),

 (39, "difference-arrays",
  "Difference arrays: range updates, cheaply",
  "You can apply a thousand range updates in O(1) each and rebuild the array at the end.",
  "Apply many range increments and then report the final array.",
  "Wide-column and time-series stores",
  "You can say what Cassandra's data model really is and when a time-series store is right.",
  "Which database would you pick for storing metrics, and why?"),

 (40, "2d-prefix-sums",
  "2D prefix sums and inclusion-exclusion",
  "You can answer any rectangle-sum query in O(1) and derive the four-term formula yourself.",
  "Answer many rectangle-sum queries on a fixed matrix.",
  "Choosing SQL or NoSQL in an interview",
  "You can make the choice out loud, with the access patterns as your evidence.",
  "SQL or NoSQL for this system, and what made you decide?"),

 (41, "prefix-revision",
  "Prefix sums revision and mock round",
  "You can recognise a prefix-sum problem from the question alone.",
  "Two problems, no hints, talk as you go.",
  "Connection pools, ORMs, and the N+1 query",
  "You can spot an N+1 query in code and fix it.",
  "Your page makes 200 database calls per request. What happened?"),

 (42, "binary-search-idea",
  "Binary search: the idea and the invariant",
  "You can state, at every step, which half of the array still contains the answer.",
  "Search a sorted array. Why is it O(log n)?",
  "Database revision and interview questions",
  "You can answer schema, index, transaction and scaling questions about a database cold.",
  "Design and defend the database layer for an unseen product."),

 (43, "binary-search-without-bugs",
  "Writing binary search without off-by-one bugs",
  "You can write it correctly the first time, every time, using one template.",
  "Write binary search on the whiteboard. No compiler.",
  "Why interviews ask object-oriented design at all",
  "You can say what an OOP round is really testing, so you stop answering the wrong question.",
  "Design a class structure for this feature."),

 (44, "first-and-last-occurrence",
  "First and last occurrence",
  "You can find the boundaries of a repeated value in O(log n).",
  "Find the first and last position of a target in a sorted array.",
  "Classes and objects",
  "You can turn a paragraph of requirements into classes with the right responsibilities.",
  "Model a library. What are your classes?"),

 (45, "rotated-array-search",
  "Search in a rotated sorted array",
  "You can binary search data that is sorted, but not from the start.",
  "Search a rotated sorted array in O(log n).",
  "Encapsulation",
  "You can say why public fields are a design bug, with a concrete failure.",
  "Why make a field private if you are going to add a getter anyway?"),
]
