"""Days 136-180. See scripts/curriculum.py for the row shape."""

# fmt: off
DAYS = [
 (136, "dijkstra",
  "Dijkstra's algorithm",
  "You can find shortest paths with weights, and say why it needs a priority queue.",
  "Find the shortest path in a weighted graph.",
  "Elasticsearch in a design",
  "You can place a search cluster in an architecture and keep it in sync with the database.",
  "Where does Elasticsearch sit, and how does it stay up to date?"),

 (137, "bellman-ford",
  "Bellman-Ford, and what negative edges break",
  "You can say exactly why Dijkstra fails on negative weights, with an example graph.",
  "Why can't you use Dijkstra here?",
  "Time-series and metrics stores",
  "You can say why a million metric points per second do not belong in a relational table.",
  "Where would you store the metrics for this system?"),

 (138, "union-find",
  "Union-Find: the disjoint set union",
  "You can implement find and union with path compression and say why it is nearly O(1).",
  "Are these two nodes in the same group? Now merge two groups.",
  "Data warehouses: OLAP versus OLTP",
  "You can say why analytics does not run on the production database.",
  "The analytics query is locking the production table. What do you do?"),

 (139, "minimum-spanning-trees",
  "Minimum spanning trees: Kruskal and Prim",
  "You can build the cheapest connecting network and explain both greedy strategies.",
  "Connect all the cities at minimum cost.",
  "ETL, batch pipelines, and where data goes to be counted",
  "You can draw the path from production writes to a dashboard number.",
  "How does yesterday's revenue number get onto the dashboard?"),

 (140, "bipartite-graphs",
  "Bipartite graphs and two-colouring",
  "You can check whether a graph splits into two groups, and see it in real problems.",
  "Can these people be split into two teams with no conflicts?",
  "Websockets, long polling, and server-sent events",
  "You can pick the right push mechanism for a live-updating feature.",
  "How does the browser find out about a new message?"),

 (141, "multi-source-bfs",
  "Multi-source BFS and 0-1 BFS",
  "You can start BFS from many nodes at once, which collapses a whole class of problems.",
  "How long until every fresh orange rots?",
  "Push notifications, end to end",
  "You can trace a notification from your server to the phone's lock screen.",
  "How does a push notification actually reach the device?"),

 (142, "graphs-revision",
  "Graphs revision and mock round",
  "You can solve two unseen graph problems cold, including one shortest path.",
  "Two problems, no hints, talk as you go.",
  "Geospatial indexing: geohash and quadtrees",
  "You can answer find everything near me without scanning every row.",
  "How do you find all drivers within two kilometres?"),

 (143, "what-dp-is",
  "What dynamic programming actually is",
  "You can define DP as recursion plus memory, and recognise the overlapping subproblems.",
  "Why is this exponential, and how do you fix it?",
  "Bloom filters and probabilistic structures",
  "You can trade a little accuracy for a lot of memory, and say when that is safe.",
  "How do you check whether a URL has been crawled, using little memory?"),

 (144, "fibonacci-dp",
  "Fibonacci: memoisation versus tabulation",
  "You can write both forms of every DP problem and convert between them.",
  "Write it top-down. Now write it bottom-up.",
  "Building blocks revision and interview questions",
  "You can pick the right component for a requirement and justify it in one sentence.",
  "You need search, a queue, and a cache. Which technologies, and why?"),

 (145, "climbing-stairs",
  "Climbing stairs and the one-dimensional habit",
  "You can write the recurrence for a linear DP before you write any code.",
  "How many ways to climb n stairs taking one or two steps?",
  "How to run a high-level design interview: the forty-five-minute script",
  "You have a repeatable order of moves for any HLD prompt, so you never freeze.",
  "Design Twitter. You have forty-five minutes. Begin."),

 (146, "house-robber",
  "House robber and the choice at each step",
  "You can express take-it-or-leave-it as a recurrence and optimise the space.",
  "Maximise the sum with no two adjacent elements.",
  "Design a URL shortener",
  "You can design the encoding, the storage, the read path and the analytics.",
  "Design a URL shortener like bit.ly."),

 (147, "finding-the-state",
  "Finding the state: the hardest part of DP",
  "You can decide what the subproblem index means, which is where most people get stuck.",
  "What does dp[i] represent in your solution?",
  "Design a pastebin",
  "You can design text storage, expiry, and the read-heavy access pattern.",
  "Design pastebin. What happens when a paste goes viral?"),

 (148, "knapsack",
  "The 0/1 knapsack",
  "You can fill the two-dimensional table by hand and explain every cell.",
  "Maximise the value you can carry within the weight limit.",
  "Design a rate limiter, at system scale",
  "You can rate limit across many servers, with shared state and a fallback.",
  "Design a rate limiter for an API used by a million clients."),

 (149, "subset-sum",
  "Subset sum and partition problems",
  "You can turn a can-we-reach-this-total question into a boolean DP table.",
  "Can this array be split into two halves with equal sums?",
  "Design a distributed key-value store",
  "You can design partitioning, replication, and the consistency guarantee.",
  "Design a key-value store like DynamoDB."),

 (150, "coin-change",
  "Unbounded knapsack and coin change",
  "You can say what changes in the loop when an item may be reused.",
  "Find the fewest coins that make the amount.",
  "Design a distributed unique ID generator",
  "You can design IDs that are unique, roughly sortable, and generated without coordination.",
  "Generate unique IDs across a hundred servers. No central counter."),

 (151, "counting-ways",
  "Coin change II: counting the ways",
  "You can count combinations without counting the same set twice, and explain the loop order.",
  "In how many ways can you make the amount?",
  "Design a web crawler",
  "You can design politeness, deduplication, scale and the frontier queue.",
  "Design a web crawler that fetches a billion pages."),

 (152, "longest-increasing-subsequence",
  "Longest increasing subsequence",
  "You can write the O(n^2) version and then the O(n log n) one with binary search.",
  "Find the longest increasing subsequence. Can you do better than O(n^2)?",
  "Design a notification system at scale",
  "You can fan out to millions of devices without melting the sender.",
  "Design a notification system sending ten million pushes an hour."),

 (153, "longest-common-subsequence",
  "Longest common subsequence",
  "You can fill the LCS grid and reconstruct the actual subsequence, not just its length.",
  "Find the longest common subsequence of two strings.",
  "Design a news feed",
  "You can compare fan-out on write with fan-out on read and pick per user type.",
  "Design the Facebook news feed. What about a celebrity with fifty million followers?"),

 (154, "edit-distance",
  "Edit distance",
  "You can derive the three-way recurrence yourself instead of memorising it.",
  "Find the minimum number of edits to turn one string into another.",
  "Design Twitter",
  "You can design the timeline, the tweet store, the follow graph and the search path.",
  "Design Twitter."),

 (155, "string-dp",
  "String DP: palindromic substrings and subsequences",
  "You can fill a table by substring length, which is the trick these problems need.",
  "Find the longest palindromic substring. Now the longest palindromic subsequence.",
  "Design Instagram",
  "You can design uploads, the feed, storage, and the CDN path for images.",
  "Design Instagram."),

 (156, "grid-dp",
  "Grid DP: unique paths and minimum path sum",
  "You can walk a grid with DP and handle obstacles and boundaries cleanly.",
  "How many paths from the top left to the bottom right?",
  "Design WhatsApp",
  "You can design message delivery, ordering, offline users and end-to-end encryption.",
  "Design WhatsApp. What happens when the recipient is offline?"),

 (157, "stock-dp",
  "DP on decisions: buy and sell stock",
  "You can model holding and not-holding as states, which solves all six stock variants.",
  "Maximise profit with at most k transactions.",
  "Design a chat system with presence",
  "You can design online status, typing indicators and group chat at scale.",
  "Design a chat system. How do you show who is online?"),

 (158, "interval-dp",
  "Interval DP",
  "You can solve problems where the subproblem is a range, not a prefix.",
  "Burst the balloons for the maximum coins.",
  "Design YouTube",
  "You can design upload, transcoding, storage, streaming and recommendations.",
  "Design YouTube."),

 (159, "dp-on-trees",
  "DP on trees",
  "You can combine children's answers into a parent's answer, which is DP without a table.",
  "Find the maximum independent set in a tree.",
  "Design Netflix",
  "You can design the video pipeline, adaptive bitrate, and the CDN economics.",
  "Design Netflix. How is it different from YouTube?"),

 (160, "bitmask-dp",
  "Bitmask DP",
  "You can use an integer as a set and solve small-n exponential problems fast.",
  "Solve the travelling salesman for n equal to 15.",
  "Design Google Drive or Dropbox",
  "You can design file sync, chunking, deduplication and conflict resolution.",
  "Design Dropbox. Two devices edit the same file offline."),

 (161, "dp-space-optimisation",
  "Space optimisation in DP",
  "You can collapse a 2D table into one or two rows and say when that is safe.",
  "Your DP uses O(n*m) space. Can you reduce it?",
  "Design Uber",
  "You can design driver location updates, matching, pricing and trip state.",
  "Design Uber."),

 (162, "recognising-dp",
  "Recognising dynamic programming in an interview",
  "You can tell within two minutes whether a problem is greedy, DP, or search.",
  "Is this greedy or DP? How do you know?",
  "Design Google Maps",
  "You can design map tiles, routing at continent scale, and live traffic.",
  "Design Google Maps navigation."),

 (163, "dp-revision",
  "Dynamic programming revision and mock round",
  "You can solve two unseen DP problems cold, defining the state out loud first.",
  "Two problems, no hints, talk as you go.",
  "Design an e-commerce system",
  "You can design catalogue, cart, inventory and the checkout race condition.",
  "Design Amazon. Two people buy the last item at once."),

 (164, "greedy-idea",
  "Greedy: when taking the best option now is safe",
  "You can name the property a problem must have before greedy is allowed.",
  "Why does greedy work here, and not on the previous problem?",
  "Design a payment system",
  "You can design idempotency, reconciliation, ledgers, and third-party failure.",
  "Design a payment system. The bank times out after taking the money."),

 (165, "proving-greedy",
  "Proving a greedy choice, simply",
  "You can give an exchange argument in three sentences, which is what interviewers want.",
  "Convince me your greedy choice is optimal.",
  "Design a ticket booking system at scale",
  "You can handle a flash sale, seat locking, and a queue of a million users.",
  "Design ticket booking for a concert that sells out in ten seconds."),

 (166, "interval-scheduling",
  "Interval scheduling",
  "You can sort by the right field, which is the entire difficulty of these problems.",
  "Fit the maximum number of non-overlapping meetings.",
  "Design search autocomplete at scale",
  "You can design the suggestion index, the ranking, and the update pipeline.",
  "Design Google's search suggestions."),

 (167, "merging-intervals",
  "Merging intervals",
  "You can merge, insert and subtract intervals without missing an edge case.",
  "Merge all overlapping intervals.",
  "Design a leaderboard",
  "You can rank millions of players in real time and answer give me my rank.",
  "Design a game leaderboard for ten million players."),

 (168, "sweep-line",
  "Meeting rooms and the sweep line",
  "You can turn intervals into plus-one and minus-one events and sweep them.",
  "How many meeting rooms do you need?",
  "Design an ad click aggregator",
  "You can design a counting pipeline that survives duplicates and late events.",
  "Count ad clicks per minute, accurately, at a million per second."),

 (169, "jump-game",
  "Jump game and reachability",
  "You can track the furthest reachable point instead of searching every path.",
  "Can you reach the last index?",
  "Design a distributed job scheduler",
  "You can design scheduling, retries, and exactly-once-ish execution across workers.",
  "Design a system that runs a million cron jobs reliably."),

 (170, "greedy-revision",
  "Greedy and intervals revision and mock round",
  "You can solve two unseen greedy problems and justify the greedy choice.",
  "Two problems, no hints, talk as you go.",
  "High-level design revision and full mock",
  "You can take an unseen HLD prompt to a defended architecture in forty-five minutes.",
  "Design a system you have never seen before. Forty-five minutes."),

 (171, "binary-and-bits",
  "Binary, bits, and why they matter",
  "You can convert between binary and decimal and read a bit pattern without panic.",
  "What is 13 in binary? What does shifting left by one do?",
  "Monitoring, metrics, and alerting",
  "You can say what you would measure and what would page you at three in the morning.",
  "What metrics would you put on the dashboard for this system?"),

 (172, "bit-tricks",
  "The bit tricks every interview uses",
  "You can count set bits, check powers of two, and clear the lowest bit, from memory.",
  "Count the number of ones in the binary representation.",
  "Logging and distributed tracing",
  "You can follow one request across eight services and find where it got slow.",
  "A request took four seconds. How do you find out which service was slow?"),

 (173, "xor",
  "XOR problems",
  "You can use XOR to cancel pairs, which solves a whole family of interview questions.",
  "Every number appears twice except one. Find it, in O(1) space.",
  "SLAs, SLOs, and error budgets",
  "You can translate 99.9 percent uptime into minutes and into engineering decisions.",
  "What does three nines mean in minutes per month?"),

 (174, "number-theory",
  "Primes, GCD, and modular arithmetic",
  "You can sieve primes, compute a GCD, and do modular arithmetic without overflow worry.",
  "Find all primes below one million.",
  "Deployments: blue-green, canary, and rollback",
  "You can ship a risky change without a night of downtime.",
  "How do you deploy a change to a service handling live traffic?"),

 (175, "combinatorics",
  "The combinatorics you actually need",
  "You can count arrangements and choices, and compute nCr without overflow.",
  "How many ways can you arrange these? Now with repetitions.",
  "Security in a design interview",
  "You can cover authentication, encryption, secrets and the common attacks in three minutes.",
  "What are the security concerns in this design?"),

 (176, "bits-maths-revision",
  "Bits and maths revision and mock round",
  "You can solve two unseen bit or maths problems cold.",
  "Two problems, no hints, talk as you go.",
  "Cost: the constraint nobody mentions",
  "You can put a monthly bill on your architecture, which almost no candidate does.",
  "What does this system cost to run per month?"),

 (177, "the-patterns-on-one-page",
  "The twenty patterns, on one page",
  "You can name the pattern for any problem you have seen, from a one-line summary.",
  "Given this problem, which pattern, and why that one?",
  "Microservices versus monolith, argued both ways",
  "You can take either side convincingly, which is what the question is testing.",
  "Would you build this as microservices? Now argue the opposite."),

 (178, "thinking-out-loud",
  "How to think out loud in a coding round",
  "You have a script for the first five minutes, so you never freeze at the start.",
  "Talk me through your approach before you write any code.",
  "The system design interview framework, memorised",
  "You can run requirements, estimation, API, data model, architecture and deep-dive in order.",
  "Design something. Show me your process, not just your answer."),

 (179, "full-coding-mock",
  "Full mock: two problems, forty-five minutes",
  "You can perform under a clock, with someone watching, which is a separate skill.",
  "One medium, one hard. The clock is running.",
  "Full mock: one high-level design, one low-level design",
  "You can survive a back-to-back design loop.",
  "Two design rounds, back to back. Begin."),

 (180, "final-revision",
  "Final revision, and the week before the interview",
  "You know exactly what to revise in the last seven days, and what to leave alone.",
  "Tell me about a problem you found hard, and what you learned from it.",
  "Final revision, and the week before the interview",
  "You have a one-page checklist for both design rounds and the behavioural round.",
  "Do you have any questions for us?"),
]
# fmt: on
