"""Days 46-90. See scripts/curriculum.py for the row shape."""

DAYS = [
 (46, "binary-search-on-the-answer",
  "Binary search on the answer",
  "You can search a range of possible answers when the array itself is not what is sorted.",
  "Find the smallest capacity that lets you ship all packages within d days.",
  "Inheritance and its costs",
  "You can use inheritance where it fits and name the three places it goes wrong.",
  "When does inheritance become a problem?"),

 (47, "minimise-the-maximum",
  "Minimise the maximum: the capacity family",
  "You can recognise minimise-the-maximum wording and turn it into a yes-or-no predicate.",
  "Split the array into k parts, minimising the largest part sum.",
  "Polymorphism",
  "You can explain polymorphism with code, not with a dictionary definition.",
  "What is polymorphism? Show me, do not tell me."),

 (48, "binary-search-on-floats",
  "Binary search on floats, and the epsilon question",
  "You can binary search a continuous range and decide when to stop.",
  "Find the square root of a number to six decimal places, without the library call.",
  "Abstraction and interfaces",
  "You can design to an interface so a swap of implementation touches one line.",
  "How would you make it easy to swap the payment provider later?"),

 (49, "peak-finding",
  "Peak finding, and searching data that is structured but not sorted",
  "You can binary search using local structure alone, with no global ordering.",
  "Find a peak element in O(log n).",
  "Composition over inheritance",
  "You can rewrite an inheritance tree as composition and say what improved.",
  "Refactor this class hierarchy. Why is your version better?"),

 (50, "binary-search-revision",
  "Binary search revision and mock round",
  "You can solve two unseen binary search problems, including one search-on-answer.",
  "Two problems, no hints, talk as you go.",
  "Class diagrams and the UML you will actually draw",
  "You can draw a class diagram on a whiteboard that an interviewer can read.",
  "Draw the class diagram for what you just described."),

 (51, "why-sorting-matters",
  "Why sorting matters more than any single sorting algorithm",
  "You reach for sort as a preprocessing step and can justify the extra n log n.",
  "Would sorting first make this problem easier?",
  "Modelling a real domain",
  "You can turn a page of product requirements into objects, fields and relationships.",
  "Here are the requirements. Model it."),

 (52, "quadratic-sorts",
  "Bubble, selection and insertion sort, and what each one teaches",
  "You can write all three and say the one case where insertion sort genuinely wins.",
  "Write insertion sort. When would you actually use it?",
  "Common object-oriented interview questions",
  "You can answer the standard OOP questions without reciting a textbook.",
  "What is the difference between an abstract class and an interface?"),

 (53, "merge-sort",
  "Merge sort",
  "You can write merge sort and explain the divide-and-conquer shape it teaches.",
  "Write merge sort. Why is it O(n log n)?",
  "Writing clean, testable classes",
  "You can inject dependencies so your class can be tested without a database.",
  "How would you unit test this class?"),

 (54, "quicksort",
  "Quicksort and partitioning",
  "You can partition an array in place and explain the worst case and how to avoid it.",
  "Write quicksort. What is its worst case, and when does it happen?",
  "Object-oriented design revision and interview questions",
  "You can take an unseen LLD prompt and produce classes in twenty minutes.",
  "Design the classes for a hotel booking system."),

 (55, "quickselect",
  "Quickselect: finding the Kth largest without sorting",
  "You can find the Kth largest in expected O(n) and say why the expectation matters.",
  "Find the Kth largest element. Can you beat O(n log n)?",
  "Single responsibility",
  "You can spot a class doing two jobs and split it.",
  "This class is 800 lines. What is wrong with it?"),

 (56, "non-comparison-sorts",
  "Counting sort, radix sort, and bucket sort",
  "You can sort in O(n) when the values are bounded, and say exactly when that is allowed.",
  "Sort a million integers in the range 0 to 100. Can you beat n log n?",
  "Open for extension, closed for modification",
  "You can add a new behaviour without editing existing code, and show it.",
  "A new discount type arrives every month. How do you design for that?"),

 (57, "stability-and-pythons-sort",
  "Stability, and what Python's sort actually does",
  "You know what stable means, why it matters, and roughly how Timsort works.",
  "Is Python's sort stable? Why do you care?",
  "Liskov substitution",
  "You can name the classic square-rectangle failure and avoid writing your own version.",
  "Is a Square a Rectangle? Defend your answer in code."),

 (58, "custom-comparators",
  "Custom comparators and sorting by keys",
  "You can sort by two fields in opposite directions without writing a comparator class.",
  "Sort by score descending, then by name ascending.",
  "Interface segregation",
  "You can spot a fat interface and split it by client.",
  "Why is a single large interface a problem?"),

 (59, "sorting-revision",
  "Sorting revision and mock round",
  "You can solve two unseen sorting problems and defend your algorithm choice.",
  "Two problems, no hints, talk as you go.",
  "Dependency inversion",
  "You can invert a dependency so the high-level policy stops importing the low-level detail.",
  "Your service imports the MySQL driver directly. What is wrong with that?"),

 (60, "hash-tables",
  "Hash tables: how a dictionary finds anything instantly",
  "You can explain hashing, buckets and O(1) average lookup with a drawing.",
  "How does a hash map work internally?",
  "DRY, KISS, and YAGNI",
  "You can tell real duplication from coincidental similarity.",
  "Is this duplication worth removing?"),

 (61, "collisions",
  "Collisions, and why a hash map can turn slow",
  "You can describe chaining and open addressing, and the worst case of each.",
  "What is the worst-case complexity of a hash map lookup? When does it happen?",
  "Coupling, cohesion, and code smells",
  "You can name what is wrong with a bad module in the vocabulary reviewers use.",
  "Review this module. What would you change?"),

 (62, "sets",
  "Sets: membership, deduplication, and the O(1) habit",
  "You replace a nested loop with a set lookup by reflex.",
  "Find the duplicate. Now do it in one pass.",
  "Design principles revision and interview questions",
  "You can critique an unseen design using SOLID without sounding like a textbook.",
  "Here is a class. Which principles does it violate?"),

 (63, "counting-with-dicts",
  "Counting with dictionaries",
  "You can build, update and query frequency maps without KeyError.",
  "Find the top k most frequent elements.",
  "What a design pattern actually is",
  "You can say why patterns exist and stop applying them where they do not belong.",
  "Which design patterns have you used, and why?"),

 (64, "grouping",
  "Grouping: the key-design skill",
  "You can invent the right dictionary key for a grouping problem, which is the whole trick.",
  "Group these strings into anagram groups. What is your key?",
  "Singleton",
  "You can implement it, and say why many engineers consider it an anti-pattern.",
  "Implement a thread-safe singleton. Now tell me why I should not use it."),

 (65, "hashing-custom-objects",
  "Hashing your own objects",
  "You can make a custom class usable as a dictionary key without subtle bugs.",
  "Why did putting this object in a set not deduplicate it?",
  "Factory and abstract factory",
  "You can hide object creation behind a factory and say what that buys you.",
  "How do you create the right notification object for each channel?"),

 (66, "when-hashing-is-wrong",
  "When a hash map is the wrong answer",
  "You can name the three cases where sorting or an array beats a dictionary.",
  "You used a hash map. Could you do it with O(1) space instead?",
  "Builder",
  "You can build an object with fifteen optional fields without a fifteen-argument constructor.",
  "This constructor takes twelve parameters. Fix it."),

 (67, "hashing-revision",
  "Hashing revision and mock round",
  "You can solve two unseen hash-map problems cold.",
  "Two problems, no hints, talk as you go.",
  "Prototype, and cloning objects",
  "You can copy an object correctly and explain shallow versus deep copy.",
  "What is the difference between a shallow copy and a deep copy?"),

 (68, "stacks",
  "Stacks: last in, first out",
  "You can implement a stack and recognise the problems that want one.",
  "Implement a stack. What operations must be O(1)?",
  "Adapter",
  "You can make two incompatible interfaces work together without editing either.",
  "You must integrate a third-party SDK with a different interface. How?"),

 (69, "balanced-brackets",
  "Balanced brackets and the parsing family",
  "You can validate nested structures and evaluate simple expressions with a stack.",
  "Check whether the brackets in this string are balanced.",
  "Decorator",
  "You can add behaviour to an object at runtime without subclassing it.",
  "Add logging and caching to this service without changing its code."),

 (70, "min-stack",
  "Min stack, and stacks that carry extra state",
  "You can get the minimum of a stack in O(1) and explain the two standard tricks.",
  "Design a stack that returns its minimum in constant time.",
  "Facade and proxy",
  "You can hide a messy subsystem behind one clean entry point.",
  "Your checkout touches six services. How do you expose it to the client?"),

 (71, "monotonic-stack",
  "Monotonic stack: the next greater element",
  "You can solve the whole next-greater and next-smaller family in O(n).",
  "For every element, find the next greater element to its right.",
  "Strategy",
  "You can swap an algorithm at runtime without a chain of if-statements.",
  "The pricing rule changes per country. How do you structure that?"),

 (72, "largest-rectangle",
  "Largest rectangle in a histogram",
  "You can solve the hardest classic monotonic-stack problem and explain each pop.",
  "Find the largest rectangle in the histogram.",
  "Observer",
  "You can notify many listeners of one event without coupling them to the source.",
  "When an order is placed, five things must happen. Design that."),

 (73, "queues",
  "Queues: first in, first out",
  "You can implement a queue with O(1) enqueue and dequeue and say why a list is wrong.",
  "Implement a queue. Why not just use a list and pop(0)?",
  "State",
  "You can model an object whose behaviour changes with its state, without a giant switch.",
  "Model an order that moves through placed, paid, shipped and delivered."),

 (74, "deques-and-window-max",
  "Deques and the sliding-window maximum",
  "You can maintain a window maximum in O(n) total using a monotonic deque.",
  "Find the maximum in every window of size k.",
  "Command and chain of responsibility",
  "You can turn an action into an object, which makes undo and queuing possible.",
  "Design undo and redo for a text editor."),

 (75, "queue-from-stacks",
  "A queue from two stacks, and a stack from queues",
  "You can build one from the other and give the amortised cost honestly.",
  "Implement a queue using only stacks. What is the amortised cost?",
  "Template method and iterator",
  "You can fix the skeleton of an algorithm and let subclasses fill in the steps.",
  "Three report types share 80 percent of their logic. Structure it."),

 (76, "lru-cache",
  "LRU cache: the structure interviewers love",
  "You can build an LRU cache with O(1) get and put and explain both data structures.",
  "Design an LRU cache with O(1) get and put.",
  "Design patterns revision and interview questions",
  "You can pick and defend a pattern for an unseen problem, or argue that none is needed.",
  "Which pattern fits here, and what would you lose by using it?"),

 (77, "stacks-queues-revision",
  "Stacks and queues revision and mock round",
  "You can solve two unseen stack or queue problems cold.",
  "Two problems, no hints, talk as you go.",
  "How to run a low-level design interview: the forty-minute script",
  "You have a repeatable order of moves for any LLD prompt, so you never freeze.",
  "Design a parking lot. You have forty minutes. Begin."),

 (78, "nodes-and-links",
  "Nodes and links: pointers without pointers",
  "You can draw a linked list in memory and say why it is not an array.",
  "What is a linked list, and when is it better than an array?",
  "Design a parking lot",
  "You can produce classes, an interface for pricing, and a spot-allocation strategy.",
  "Design a parking lot. Multiple floors, multiple vehicle types."),

 (79, "list-traversal",
  "Traversal, insertion, and deletion",
  "You can insert and delete at any position without losing the rest of the list.",
  "Delete the node at position k. What if it is the head?",
  "Design an elevator system",
  "You can model requests, scheduling and direction without hand-waving the algorithm.",
  "Design an elevator system for a ten-storey building with three lifts."),

 (80, "dummy-head",
  "The dummy head trick",
  "You stop writing a special case for the head, in every linked list problem.",
  "Remove all nodes with a given value, including at the head.",
  "Design an ATM",
  "You can model the state machine, the cash dispenser, and the failure cases.",
  "Design an ATM. What happens if the network dies mid-withdrawal?"),

 (81, "reversing-a-list",
  "Reversing a linked list",
  "You can reverse a list iteratively and recursively and draw the pointer moves.",
  "Reverse a linked list. Now do it in groups of k.",
  "Design a vending machine",
  "You can model the coin-and-selection state machine cleanly.",
  "Design a vending machine. Handle exact change and refunds."),

 (82, "runner-technique",
  "Finding the middle, and the runner technique",
  "You can find the middle and the Nth from the end in a single pass.",
  "Remove the Nth node from the end in one pass.",
  "Design a library management system",
  "You can model members, catalogues, loans and fines with the right responsibilities.",
  "Design a library system. Who owns the rule about late fees?"),

 (83, "cycle-detection",
  "Cycle detection, and why Floyd's algorithm works",
  "You can detect a cycle, find where it starts, and explain the two-pointer proof simply.",
  "Detect a cycle in a linked list. Now find the node where it begins.",
  "Design tic-tac-toe, and then chess",
  "You can design a board game so the rules live in one replaceable place.",
  "Design tic-tac-toe. Now make it work for an N by N board."),

 (84, "merging-and-sorting-lists",
  "Merging and sorting linked lists",
  "You can merge two sorted lists and sort a list in O(n log n) without extra arrays.",
  "Merge two sorted linked lists. Now sort an unsorted one.",
  "Design a deck of cards and a card game",
  "You can model shuffling, dealing and hand comparison cleanly.",
  "Design a deck of cards. Now build blackjack on top of it."),

 (85, "doubly-and-circular",
  "Doubly and circular linked lists",
  "You can splice a node out in O(1) and say what the extra pointer costs.",
  "Why does an LRU cache use a doubly linked list?",
  "Design Splitwise",
  "You can model groups, expenses, splits and settlement, with the simplification algorithm.",
  "Design Splitwise. How do you minimise the number of transactions?"),

 (86, "linked-lists-revision",
  "Linked lists revision and mock round",
  "You can solve two unseen pointer-surgery problems cold.",
  "Two problems, no hints, talk as you go.",
  "Design BookMyShow",
  "You can model shows, seats and the booking lock that stops double-selling a seat.",
  "Design BookMyShow. Two users click the same seat at the same moment."),

 (87, "recursion-leap-of-faith",
  "Recursion: the leap of faith",
  "You can write a recursive function by trusting it on the smaller input.",
  "Solve this recursively. What is the base case?",
  "Design a food delivery order flow",
  "You can model restaurants, carts, orders and the delivery state machine.",
  "Design the order flow for a food delivery app."),

 (88, "the-call-stack",
  "The call stack, drawn",
  "You can trace a recursive call by hand and read a RecursionError correctly.",
  "Trace this recursion. What is on the stack at the deepest point?",
  "Design a ride-hailing booking flow",
  "You can model riders, drivers, matching and trip state at the object level.",
  "Design the booking flow for a cab app."),

 (89, "recursion-that-terminates",
  "Writing a recursive function that terminates",
  "You can name the value that shrinks on every call, so your recursion always ends.",
  "Why does your recursion terminate?",
  "Design a rate limiter, at the object level",
  "You can implement fixed window, sliding window and token bucket as classes.",
  "Implement a rate limiter class. Which algorithm, and why?"),

 (90, "recursion-on-arrays",
  "Recursion on arrays and strings",
  "You can convert any simple loop into recursion, and back again.",
  "Reverse a string recursively. Now do it without extra space.",
  "Design an in-memory cache with eviction",
  "You can design a cache with a pluggable eviction policy and a TTL.",
  "Design an in-memory cache. Now make the eviction policy swappable."),
]
