"""Days 91-135. See scripts/curriculum.py for the row shape."""

# fmt: off
DAYS = [
 (91, "subsets",
  "Subsets: the include-or-exclude tree",
  "You can generate every subset and draw the decision tree that produced them.",
  "Generate all subsets of this array.",
  "Design a logging framework",
  "You can design log levels, appenders and formatters as replaceable parts.",
  "Design a logging library. How do I add a new destination?"),

 (92, "permutations",
  "Permutations",
  "You can generate every ordering, with and without duplicates.",
  "Generate all permutations. Now handle duplicate values.",
  "Design a notification service",
  "You can model channels, templates, user preferences and retries.",
  "Design a notification service that supports email, SMS and push."),

 (93, "combinations",
  "Combinations and combination sum",
  "You can enumerate choices without repeating the same set in a different order.",
  "Find all combinations that sum to the target.",
  "Design a file system",
  "You can model files, directories and paths, and support search.",
  "Design an in-memory file system."),

 (94, "backtracking",
  "Backtracking: the undo step",
  "You can add, recurse, and remove, and say why the removal is the whole pattern.",
  "Why did you pop that element after the recursive call?",
  "Design snake and ladder",
  "You can model the board, the dice and the players with clean separation.",
  "Design snake and ladder for n players."),

 (95, "n-queens",
  "N-Queens and constraint grids",
  "You can prune a search tree with a validity check and count the work you avoided.",
  "Place n queens on an n by n board.",
  "Design an online auction",
  "You can model bids, the closing rule, and concurrent bidding.",
  "Design an auction site. Two bids arrive in the same millisecond."),

 (96, "grid-backtracking",
  "Sudoku, word search, and grid backtracking",
  "You can search a two-dimensional space with backtracking and mark visited cells safely.",
  "Solve the sudoku board. Now find the word in the grid.",
  "Low-level design revision and full mock",
  "You can take an unseen LLD prompt to a defended class diagram in forty minutes.",
  "Design a chess game. Forty minutes. Begin."),

 (97, "recursion-revision",
  "Recursion and backtracking revision and mock round",
  "You can solve two unseen backtracking problems cold.",
  "Two problems, no hints, talk as you go.",
  "What scale actually means, in numbers",
  "You stop saying millions of users and start saying requests per second.",
  "This app has ten million users. What is the read QPS?"),

 (98, "what-a-tree-is",
  "What a tree is, and the vocabulary you need",
  "You can use root, leaf, height, depth, parent and subtree correctly and without hesitation.",
  "What is the height of this tree? What is the depth of that node?",
  "Vertical versus horizontal scaling",
  "You can say when buying a bigger machine is the right answer.",
  "Your database is at capacity. Bigger box, or more boxes?"),

 (99, "binary-trees-in-code",
  "Binary trees in code",
  "You can define a node class and build a tree by hand for testing.",
  "Build this tree in code. Now print it.",
  "Load balancers",
  "You can name the layer, the algorithms, and what happens on health-check failure.",
  "How does a load balancer decide which server gets the request?"),

 (100, "dfs-traversals",
  "Depth-first traversal: preorder, inorder, postorder",
  "You can write all three recursively and say which problem needs which order.",
  "Print the tree in inorder. Now do it iteratively.",
  "Stateless services and why they scale",
  "You can explain why sticky sessions are a scaling bug.",
  "Why should a web server be stateless?"),

 (101, "bfs-level-order",
  "Breadth-first traversal: level order",
  "You can process a tree level by level and know exactly where the level boundary is.",
  "Print the tree level by level. Now print each level as its own list.",
  "Caching: the single biggest win",
  "You can place a cache at four different layers and say what each one saves.",
  "Where would you put a cache in this system?"),

 (102, "height-and-diameter",
  "Height, depth, and diameter",
  "You can compute the diameter in one pass, using the height as a by-product.",
  "Find the diameter of the binary tree in O(n).",
  "Cache invalidation and eviction policies",
  "You can pick write-through, write-back or write-around and defend it.",
  "How do you keep the cache consistent with the database?"),

 (103, "tree-comparisons",
  "Same tree, symmetric tree, and subtree",
  "You can compare two trees structurally and handle the null cases without crashing.",
  "Are these two trees identical? Is this tree a subtree of that one?",
  "Content delivery networks",
  "You can say what a CDN caches, where it sits, and what it cannot help with.",
  "Would a CDN help this system? What would it not help with?"),

 (104, "tree-path-problems",
  "Path problems, and the return-value trick",
  "You can return one thing to the parent while tracking another in an outer variable.",
  "Find the maximum path sum in the binary tree.",
  "Database replication",
  "You can draw leader-follower replication and say what happens when the leader dies.",
  "How do you make the database survive a machine failure?"),

 (105, "lowest-common-ancestor",
  "Lowest common ancestor",
  "You can find the LCA in a general binary tree and in a BST, and know why they differ.",
  "Find the lowest common ancestor of these two nodes.",
  "Read replicas and replication lag",
  "You can explain why a user sometimes does not see their own write.",
  "The user posted a comment and cannot see it. What happened?"),

 (106, "bst-property",
  "Binary search trees: the ordering property",
  "You can state the BST invariant precisely, including the whole-subtree part.",
  "What makes a tree a binary search tree?",
  "Sharding, part one: choosing the key",
  "You can pick a shard key and predict which queries it will make expensive.",
  "How would you shard this table? What breaks after you do?"),

 (107, "bst-operations",
  "BST insert, search, and delete",
  "You can delete a node with two children and explain the successor swap.",
  "Delete this node from the BST. It has two children.",
  "Sharding, part two: rebalancing and hot spots",
  "You can describe resharding without downtime and identify a hot shard.",
  "One shard is taking 60 percent of the traffic. Now what?"),

 (108, "validating-a-bst",
  "Validating a binary search tree",
  "You avoid the classic wrong answer and can show the input that kills it.",
  "Is this a valid BST? Are you sure your check is correct?",
  "Consistent hashing",
  "You can explain why adding a server does not reshuffle every key.",
  "You add a cache node. How many keys move?"),

 (109, "balanced-trees",
  "Balanced trees, and why balance matters",
  "You can show the input that turns a BST into a linked list, and name the fix.",
  "What is the worst case for a BST? How do real databases avoid it?",
  "Back-of-the-envelope estimation",
  "You can produce QPS, storage and bandwidth numbers out loud in three minutes.",
  "Estimate the storage for five years of this system's data."),

 (110, "trees-from-traversals",
  "Building a tree from its traversals",
  "You can reconstruct a tree from preorder plus inorder, and say why postorder plus preorder fails.",
  "Build the tree from its preorder and inorder traversals.",
  "Capacity planning: QPS, storage, bandwidth",
  "You can turn a product requirement into a server count.",
  "How many servers does this system need?"),

 (111, "serialise-a-tree",
  "Serialising and deserialising a tree",
  "You can turn a tree into a string and back, preserving structure including nulls.",
  "Serialise this tree, then rebuild it from the string.",
  "Single points of failure",
  "You can look at an architecture diagram and circle every box that kills the system.",
  "Which component here takes the whole system down if it fails?"),

 (112, "trees-revision",
  "Trees revision and mock round",
  "You can solve two unseen tree problems cold.",
  "Two problems, no hints, talk as you go.",
  "Scaling revision and interview questions",
  "You can scale an unseen read-heavy system from one box to many, out loud.",
  "This service is falling over at 10000 QPS. Walk me through fixing it."),

 (113, "the-heap",
  "The heap: a tree stored in an array",
  "You can compute parent and child indices and explain the heap property.",
  "What is a heap? Where is the parent of index i?",
  "Why distributed systems are hard",
  "You can name the three things that stop being true once there are two machines.",
  "What changes when you go from one server to two?"),

 (114, "heapify",
  "Push, pop, and heapify",
  "You can sift up and sift down by hand, and know why build-heap is O(n).",
  "Insert into the heap. Now remove the minimum.",
  "The CAP theorem, honestly",
  "You can state CAP correctly and stop misusing the word availability.",
  "Explain CAP. Which one does your design give up?"),

 (115, "heapq",
  "Python's heapq, and the min-heap-only problem",
  "You can simulate a max-heap and store tuples with tie-breakers safely.",
  "Python only has a min-heap. How do you get the maximum?",
  "Consistency models",
  "You can order strong, causal and eventual consistency and give an example of each.",
  "What consistency does this feature need? Justify it."),

 (116, "top-k",
  "Top K problems",
  "You can choose between a heap, a sort and quickselect and defend the choice with n and k.",
  "Find the k largest elements. Which approach, and why?",
  "Eventual consistency in practice",
  "You can design a feature that stays usable while the data is briefly stale.",
  "The like count is wrong for two seconds. Is that acceptable?"),

 (117, "merge-k-sorted",
  "Merging K sorted lists",
  "You can merge k lists in O(n log k) and explain why the heap holds only k items.",
  "Merge k sorted lists efficiently.",
  "Quorums: why R plus W must exceed N",
  "You can compute a quorum and show why the inequality guarantees an overlap.",
  "You have five replicas. What R and W would you pick?"),

 (118, "two-heaps",
  "Two heaps: the running median",
  "You can keep a stream balanced across two heaps and read the median in O(1).",
  "Find the median of a stream of numbers.",
  "Leader election",
  "You can say why a system needs one leader and how it picks a new one.",
  "The leader crashed. How does the cluster choose the next one?"),

 (119, "heaps-revision",
  "Heaps revision and mock round",
  "You can solve two unseen heap problems cold.",
  "Two problems, no hints, talk as you go.",
  "Consensus, and Raft in plain English",
  "You can explain how a group of machines agrees on one value, without the paper.",
  "How do the replicas agree on the order of writes?"),

 (120, "the-trie",
  "The trie: a tree of characters",
  "You can draw a trie for five words and see why prefixes are shared.",
  "What is a trie, and what is it good at?",
  "Distributed transactions and two-phase commit",
  "You can describe 2PC and name the failure that makes it dangerous.",
  "How do you make a transfer atomic across two services?"),

 (121, "trie-operations",
  "Insert, search, and prefix search",
  "You can implement all three and state the complexity in terms of word length.",
  "Implement a trie with insert, search and startsWith.",
  "The saga pattern",
  "You can replace a distributed transaction with compensating actions.",
  "Booking a trip touches flights, hotels and payments. Design it."),

 (122, "autocomplete",
  "Autocomplete and word dictionaries",
  "You can return the top suggestions for a prefix and say what you store at each node.",
  "Design autocomplete for a search box.",
  "Idempotency and exactly-once delivery",
  "You can design an operation that is safe to retry, and explain why exactly-once is a lie.",
  "The payment request timed out. Is it safe to retry?"),

 (123, "word-search-ii",
  "Tries in interviews: word search II",
  "You can combine a trie with backtracking and explain why that beats searching each word.",
  "Find all dictionary words in the letter grid.",
  "Clocks, ordering, and why time is a lie",
  "You can explain why two servers disagree about which event came first.",
  "Two events have the same timestamp. Which happened first?"),

 (124, "tries-revision",
  "Tries revision and mock round",
  "You can solve two unseen trie problems cold.",
  "Two problems, no hints, talk as you go.",
  "Failure detection, heartbeats, and timeouts",
  "You can say why a slow node and a dead node look identical, and design around it.",
  "How do you know a server has died?"),

 (125, "what-a-graph-is",
  "What a graph is, and where graphs hide",
  "You can see the graph inside a problem that never uses the word.",
  "Is this a graph problem? What are the nodes and edges?",
  "Retries, backoff, and thundering herds",
  "You can design a retry policy that does not amplify an outage.",
  "Everything retried at once and the service died. What went wrong?"),

 (126, "graph-representation",
  "Representing a graph: adjacency matrix versus adjacency list",
  "You can choose the representation from the density and say what each costs.",
  "How will you store this graph? Why not the other way?",
  "Circuit breakers and bulkheads",
  "You can stop one failing dependency from taking down the whole service.",
  "One downstream service is slow. How do you protect the rest?"),

 (127, "graph-bfs",
  "Breadth-first search on a graph",
  "You can write BFS with a queue and a visited set, and never revisit a node.",
  "Traverse this graph breadth-first.",
  "Distributed locks",
  "You can implement one and name the failure mode that makes it unsafe.",
  "Implement a distributed lock. What if the holder crashes?"),

 (128, "graph-dfs",
  "Depth-first search on a graph",
  "You can write DFS recursively and iteratively, and handle disconnected graphs.",
  "Traverse this graph depth-first. What if it is disconnected?",
  "Distributed systems revision and interview questions",
  "You can reason about consistency, failure and coordination in an unseen design.",
  "Your write succeeded on two of three replicas. What do you tell the user?"),

 (129, "connected-components",
  "Connected components",
  "You can count the separate pieces of a graph and use that in real problems.",
  "How many connected components does this graph have?",
  "Message queues: why async changes everything",
  "You can move work off the request path and say what the user experience becomes.",
  "The signup email takes four seconds. Fix the latency."),

 (130, "grids-are-graphs",
  "Grids are graphs: islands and flood fill",
  "You can treat a matrix as a graph and get the neighbour logic right every time.",
  "Count the number of islands in this grid.",
  "Kafka, explained",
  "You can describe topics, partitions, offsets and consumer groups accurately.",
  "How does Kafka guarantee ordering?"),

 (131, "unweighted-shortest-path",
  "Shortest path in an unweighted graph",
  "You can prove that BFS gives the shortest path when every edge costs the same.",
  "Find the shortest path from A to B. Why does BFS work here?",
  "Publish-subscribe versus point-to-point",
  "You can pick the right messaging shape for a given requirement.",
  "One event, five consumers. Queue or topic?"),

 (132, "undirected-cycles",
  "Cycle detection in an undirected graph",
  "You can detect a cycle while handling the parent edge correctly.",
  "Does this undirected graph contain a cycle?",
  "Stream processing basics",
  "You can explain windowing, watermarks and late events without jargon.",
  "How do you count events per minute when events arrive late?"),

 (133, "directed-cycles",
  "Cycle detection in a directed graph",
  "You can use three colours or a recursion stack, and say why the undirected method fails.",
  "Does this directed graph contain a cycle?",
  "Object storage, S3-style",
  "You can say what object storage is for and why it is not a file system.",
  "Where do the uploaded images actually go?"),

 (134, "topological-sort",
  "Topological sort",
  "You can order tasks by dependency with Kahn's algorithm and with DFS.",
  "Order these tasks so that every dependency comes first.",
  "Blob storage versus storing files in the database",
  "You can argue the trade-off with numbers, not opinion.",
  "Should the images go in the database? Defend your answer."),

 (135, "dependency-problems",
  "Course schedule and the dependency family",
  "You can spot that a problem is topological sort even when it mentions no graph.",
  "Can all courses be finished? Now give me a valid order.",
  "Search: how a search index actually works",
  "You can explain an inverted index and why LIKE does not scale.",
  "How does full-text search work? Why not just use LIKE?"),
]
# fmt: on
