"""Days 1-45: foundations (1-15) and advanced features (16-45).

Row shape: (n, slug, theme, py_title, go_title, cpp_title, outcome, ask)
See ../../curriculum.py.
"""

# fmt: off
DAYS = [
 # ---------------- Phase 1: Foundations (1-15) ----------------
 (1, "hello-three-languages", "Toolchain and the first program",
  "python3, a file, and the interpreter",
  "go run, go build, and the Go toolchain",
  "g++, a file, and the compiler",
  "You can install all three toolchains, run a program in each, and read the first error each one gives you.",
  "What actually happens between saving the file and seeing the output?"),

 (2, "variables-and-types", "Variables, types, and numbers",
  "Dynamic names, int without limits, float with them",
  "Static types, int64, and := versus var",
  "Fixed-width ints, overflow, and auto",
  "You can declare a number in each language, say how wide it is, and predict what 2 000 000 000 + 2 000 000 000 prints.",
  "What is the difference between a statically and a dynamically typed language?"),

 (3, "strings-and-text", "Strings and text",
  "Immutable str, f-strings, and slicing",
  "Strings are bytes, runes are characters, fmt.Sprintf",
  "std::string, string literals, and std::format",
  "You can build, slice, search and format text in each language, and say why a Hindi word has a different length in each.",
  "Why does the length of a string not always equal the number of characters?"),

 (4, "conditions-and-loops", "Conditions and loops",
  "if/elif/else, for-in, while, break and continue",
  "if with init statements, the only loop is for, switch without fallthrough",
  "if, for, while, do-while, range-for, switch with fallthrough",
  "You can write every loop shape in each language and pick the one that reads cleanest for a given job.",
  "Write a loop that stops early. Now write it without break."),

 (5, "functions", "Functions",
  "def, default arguments, *args, **kwargs, and returning anything",
  "func, multiple return values, named results, variadic",
  "Declarations, definitions, overloading, default arguments",
  "You can write a function with several inputs and outputs in each language and explain where each argument lives.",
  "How does each language return more than one value?"),

 (6, "lists-slices-vectors", "Growable sequences",
  "list: append, insert, pop, slicing, and the cost of each",
  "slice: length, capacity, append, and the backing array",
  "std::vector: push_back, size, capacity, and reallocation",
  "You can grow, shrink, index and copy a sequence in each language and say when a copy really happens.",
  "What happens under the hood when you append to a full sequence?"),

 (7, "dicts-maps-sets", "Key-value and membership",
  "dict and set: hashing, ordering, and the in operator",
  "map: make, lookup with the comma-ok idiom, delete, and no order",
  "std::unordered_map, std::map, std::set, and the choice between them",
  "You can count, group and deduplicate with a map in each language and explain what happens on a missing key.",
  "What does your language do when you read a key that is not there?"),

 (8, "structs-and-classes", "Modelling a thing",
  "class, __init__, methods, and dataclasses",
  "struct, methods with receivers, and constructor functions",
  "struct, class, constructors, and member functions",
  "You can model a bank account in each language with data and behaviour together, and say what is public.",
  "What is the difference between a struct and a class?"),

 (9, "errors-three-ways", "Errors, three ways",
  "Exceptions: try, except, raise, finally",
  "Error values: if err != nil, errors.New, fmt.Errorf",
  "Exceptions and std::expected: throw, catch, and returning failure",
  "You can make a function fail in each language and make the caller handle it, and say which style each language prefers.",
  "Should this function throw, or return an error?"),

 (10, "files-and-io", "Files and standard I/O",
  "open, with, read/write, pathlib, and sys.stdin",
  "os.Open, bufio.Scanner, io.Reader and io.Writer",
  "std::ifstream, std::ofstream, std::cin, std::cout, and buffering",
  "You can read a file line by line, write one, and read from standard input in each language.",
  "How do you read a file that is bigger than memory?"),

 (11, "modules-and-packages", "Splitting code across files",
  "import, modules, packages, and the main guard",
  "package, exported names, go.mod, and internal directories",
  "Headers, translation units, #include, and namespaces",
  "You can split a program into three files in each language and explain what is visible from where.",
  "What makes a name visible to another file?"),

 (12, "pointers-and-references", "Pointers, references, and value semantics",
  "Everything is a reference to an object; is versus ==",
  "Pointers with & and *, value receivers versus pointer receivers",
  "Pointers, references, const, and passing by value",
  "You can say, for each language, whether a function receives a copy or the original, and prove it with a print.",
  "Is this passed by value or by reference?"),

 (13, "memory-who-frees-it", "Memory: who frees what",
  "Reference counting and the garbage collector",
  "The garbage collector, escape analysis, and stack versus heap",
  "RAII, new/delete, and why you almost never write delete",
  "You can say where a value lives, who frees it, and when, in each language.",
  "How does memory get freed in your language?"),

 (14, "tooling-and-project-layout", "Formatters, linters, and a real project layout",
  "uv, venv, pyproject.toml, ruff",
  "go fmt, go vet, go mod tidy, and the standard layout",
  "CMake, clang-format, and a src/include layout",
  "You can start a new project in each language from an empty folder, with formatting and dependencies working.",
  "How do you set up a new project so a teammate can build it on day one?"),

 (15, "project-1-todo-cli", "Mini project 1: a to-do CLI",
  "A to-do CLI in Python, saved as JSON",
  "A to-do CLI in Go, saved as JSON",
  "A to-do CLI in C++, saved as JSON",
  "You can build the same small tool in all three languages, run it, and say which one felt right for the job.",
  "Walk me through a small program you wrote. Why did you structure it that way?"),

 # ---------------- Phase 2: Advanced features (16-45) ----------------
 (16, "interfaces-and-duck-typing", "Interfaces",
  "Duck typing, abstract base classes, and Protocol",
  "Interfaces are satisfied implicitly; the empty interface; io.Reader",
  "Abstract classes, pure virtual functions, and vtables",
  "You can define a behaviour without naming a type in each language, and say when the check happens.",
  "What is an interface, and when does the compiler check it?"),

 (17, "composition-vs-inheritance", "Composition versus inheritance",
  "Inheritance, super(), and the MRO",
  "Struct embedding, and why Go has no inheritance",
  "Public inheritance, virtual, override, and object slicing",
  "You can extend a type in each language and say why composition is the usual answer.",
  "Why is composition preferred over inheritance?"),

 (18, "generics", "Generics",
  "typing generics: TypeVar, Generic, and list[T]",
  "Type parameters, constraints, and any versus comparable",
  "Templates, template argument deduction, and instantiation",
  "You can write one Stack that works for ints and strings in each language.",
  "How would you write a function that works for any type?"),

 (19, "closures-and-first-class-functions", "Closures",
  "Functions as values, lambda, and captured variables",
  "Function literals, captured loop variables, and function types",
  "Lambdas, capture lists by value and by reference, std::function",
  "You can return a function from a function in each language and say what it captured.",
  "What is a closure, and what does it capture?"),

 (20, "iterators-and-generators", "Iterators and generators",
  "__iter__, __next__, yield, and generator expressions",
  "Range-over-func iterators (iter.Seq) and channels as iterators",
  "Iterator categories, begin/end, and C++20 ranges",
  "You can produce values lazily in each language without building the whole list first.",
  "How do you loop over something that does not fit in memory?"),

 (21, "decorators-and-middleware", "Wrapping behaviour",
  "Decorators, functools.wraps, and decorators with arguments",
  "Middleware: functions that take and return handlers",
  "Function objects, higher-order functions, and wrapper classes",
  "You can add logging around any function in each language without touching the function.",
  "How would you add timing to every function in a module?"),

 (22, "enums-and-sum-types", "Enums and sum types",
  "Enum, IntEnum, auto, and match on enums",
  "iota, typed constants, and the Stringer pattern",
  "enum class, std::variant, and std::visit",
  "You can model one-of-three-states in each language and be told, at compile time or run time, when you miss one.",
  "How do you represent a fixed set of values?"),

 (23, "optional-and-null", "Nothing, safely",
  "None, Optional[T], and the walrus operator",
  "nil, zero values, and the nil-interface trap",
  "std::optional, nullptr, and value_or",
  "You can express 'maybe no value' in each language and say what happens when you forget to check.",
  "How does your language represent the absence of a value?"),

 (24, "pattern-matching", "Pattern matching",
  "match/case with structural patterns and guards",
  "Type switches and switch on values",
  "std::visit on variant, if constexpr, and structured bindings",
  "You can branch on the shape of data in each language.",
  "How do you handle a value that could be one of several types?"),

 (25, "operators-and-dunders", "Making your type behave like a built-in",
  "__eq__, __lt__, __add__, __repr__, __hash__",
  "No operator overloading: Stringer, sort.Slice, and cmp",
  "operator==, operator<=>, operator<<, and the rule of least surprise",
  "You can make a Money type compare, print and sort correctly in each language.",
  "How would you make your type sortable?"),

 (26, "immutability-and-const", "Immutability",
  "frozen dataclasses, tuple, frozenset, and Final",
  "const for constants only; immutability by convention",
  "const, constexpr, consteval, and const-correct methods",
  "You can mark something unchangeable in each language and say who enforces it.",
  "How do you prevent a value from being modified?"),

 (27, "error-handling-advanced", "Error handling, properly",
  "Exception hierarchies, exception chaining, and ExceptionGroup",
  "errors.Is, errors.As, %w wrapping, and sentinel errors",
  "Exception hierarchies, noexcept, and std::expected chains",
  "You can wrap an error with context in each language and unwrap it three layers up.",
  "How do you add context to an error without losing the original?"),

 (28, "testing", "Testing",
  "pytest: fixtures, parametrize, and assert introspection",
  "go test, table-driven tests, and t.Run subtests",
  "GoogleTest and CTest: TEST, EXPECT_EQ, and fixtures",
  "You can write a test file in each language and make it fail on purpose to see the report.",
  "How do you test a function with ten input cases?"),

 (29, "debugging-and-profiling", "Debugging",
  "pdb, breakpoint(), and reading a traceback",
  "delve, and reading a goroutine panic dump",
  "gdb, sanitizers, and reading a segfault",
  "You can set a breakpoint, step, and inspect a variable in each language.",
  "Your program crashes. Walk me through how you find the bug."),

 (30, "project-2-text-tool", "Mini project 2: a text analyser",
  "Word frequency and log summariser in Python",
  "Word frequency and log summariser in Go",
  "Word frequency and log summariser in C++",
  "You can build a tool that reads a large file, counts and reports, in all three, with tests.",
  "How would you find the top 10 words in a 2 GB file?"),

 (31, "concurrency-threads", "Concurrency I: threads",
  "threading.Thread, the GIL, and what it really blocks",
  "goroutines, go func(), and sync.WaitGroup",
  "std::thread, std::jthread, and join",
  "You can start ten workers in each language and wait for all of them.",
  "What is the difference between a thread and a goroutine?"),

 (32, "concurrency-channels-and-queues", "Concurrency II: passing messages",
  "queue.Queue and producer-consumer",
  "Channels: unbuffered, buffered, close, and range",
  "std::condition_variable and a hand-built thread-safe queue",
  "You can move work between threads safely in each language.",
  "How do two threads hand data to each other safely?"),

 (33, "concurrency-locks-and-races", "Concurrency III: shared memory",
  "threading.Lock, RLock, and a race you can reproduce",
  "sync.Mutex, sync.RWMutex, atomic, and go test -race",
  "std::mutex, std::lock_guard, std::atomic, and ThreadSanitizer",
  "You can write a data race in each language, detect it with a tool, and fix it.",
  "What is a data race, and how do you find one?"),

 (34, "concurrency-async", "Concurrency IV: async",
  "asyncio, await, gather, and the event loop",
  "select, and why Go does not need async/await",
  "std::async, std::future, and C++20 coroutines in outline",
  "You can make 100 network calls at once in each language and say where the waiting happens.",
  "What is the difference between concurrency and parallelism?"),

 (35, "worker-pools-and-pipelines", "Worker pools and pipelines",
  "concurrent.futures: ThreadPoolExecutor and ProcessPoolExecutor",
  "Worker pool with channels, fan-out and fan-in",
  "A thread pool class with a task queue",
  "You can run N jobs on K workers in each language and collect results in order.",
  "How would you process a million items with eight workers?"),

 (36, "timeouts-and-cancellation", "Timeouts and cancellation",
  "asyncio.timeout, Event, and cooperative cancellation",
  "context.Context: WithTimeout, WithCancel, and Done()",
  "std::stop_token, deadlines, and checking a flag",
  "You can stop a long job cleanly from the outside in each language.",
  "How do you cancel a request that is taking too long?"),

 (37, "memory-model-deep", "Memory model, deeper",
  "Object headers, refcounts, cycles, and the gc module",
  "Escape analysis, the GC pacer, and GOGC",
  "Smart pointers: unique_ptr, shared_ptr, weak_ptr",
  "You can say why a value moved to the heap in each language and what that costs.",
  "What is a memory leak in a garbage-collected language?"),

 (38, "copy-and-move", "Copies, shares, and moves",
  "Shallow copy, deepcopy, and aliasing bugs",
  "Slices share backing arrays; copy(); append aliasing",
  "Copy constructors, std::move, and the rule of five",
  "You can predict whether a change through one variable shows up in another, in each language.",
  "If I modify the copy, does the original change?"),

 (39, "unicode-and-bytes", "Text versus bytes",
  "str versus bytes, encode, decode, and UnicodeDecodeError",
  "[]byte, rune, the utf8 package, and strings.Builder",
  "char, char8_t, std::string_view, and UTF-8 by hand",
  "You can explain what a byte is, what a character is, and where each language draws the line.",
  "What is the difference between a byte and a character?"),

 (40, "json", "JSON in and out",
  "json.loads, json.dumps, dataclasses, and pydantic",
  "encoding/json, struct tags, and omitempty",
  "nlohmann/json: parsing, serialising, and from_json",
  "You can round-trip a struct through JSON in each language and handle a bad document.",
  "How do you turn a JSON document into an object?"),

 (41, "dates-times-random", "Dates, times, and randomness",
  "datetime, zoneinfo, time.monotonic, and random versus secrets",
  "time.Time, Duration, time.Now, and math/rand versus crypto/rand",
  "std::chrono, time zones, and <random>",
  "You can measure elapsed time correctly and generate a secure random token in each language.",
  "Why should you not use the wall clock to measure elapsed time?"),

 (42, "regular-expressions", "Regular expressions",
  "re: search, match, findall, groups, and compiled patterns",
  "regexp: RE2 semantics and why there is no backtracking",
  "std::regex, and why you reach for RE2 or ctre instead",
  "You can extract dates and emails from text in each language and say when regex is the wrong tool.",
  "Write a pattern that matches an email address. Now say why it is wrong."),

 (43, "reflection-and-metaprogramming", "Reflection and metaprogramming",
  "getattr, setattr, __dict__, and metaclasses in outline",
  "reflect: Type, Value, struct tags, and when to avoid it",
  "Type traits, if constexpr, and templates as compile-time code",
  "You can inspect a type at run time in each language and say what it costs.",
  "How does a JSON library know your struct's field names?"),

 (44, "build-and-packaging", "Building and shipping",
  "pyproject.toml, wheels, and PyInstaller",
  "go build flags, -ldflags, cross-compiling, and a static binary",
  "CMake targets, static versus dynamic linking, and Release builds",
  "You can produce a distributable artifact of a program in each language.",
  "How do you ship your program to a machine without the toolchain?"),

 (45, "project-3-concurrent-downloader", "Mini project 3: a concurrent downloader",
  "asyncio and httpx downloader with a progress report",
  "Goroutine worker-pool downloader with context",
  "Thread-pool downloader with libcurl",
  "You can fetch 200 URLs with a bounded pool, timeouts, and retries, in all three.",
  "How would you download a thousand files as fast as possible without overloading the server?"),
]
