"""Regenerate docs/TRACKER.md from the index and the disk. Never hand-edit the output.

Usage:
    python scripts/tracker.py --print
    python scripts/tracker.py --write
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DAYS = ROOT / "days"
INDEX = ROOT / "docs" / "CURRICULUM_INDEX.md"
OUT = ROOT / "docs" / "TRACKER.md"

PHASE_RE = re.compile(r"^##\s+Phase\s+(\d+)\s+—\s+(.+?)\s+·\s+`([A-Z]{3})`")
ROW_RE = re.compile(r"^\|\s*(\d+)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$")


def parse_index() -> list[dict]:
    rows: list[dict] = []
    phase, phase_title = None, None
    for line in INDEX.read_text(encoding="utf-8").splitlines():
        if m := PHASE_RE.match(line):
            phase, phase_title = int(m.group(1)), m.group(2)
            continue
        if line.startswith("## Phase 0"):
            phase, phase_title = 0, "The Foundry"
            continue
        if m := ROW_RE.match(line):
            title = m.group(2)
            rows.append(
                {
                    "day": int(m.group(1)),
                    "title": title.replace("**G** — ", ""),
                    "gate": "**G**" in title,
                    "ids": [i for i in re.findall(r"[A-Z]{3}-\d{2}", m.group(3))],
                    "phase": phase,
                    "phase_title": phase_title,
                }
            )
    return rows


def day_dir(n: int) -> Path | None:
    """The folder for day n, found by its number: day-NN-<slug>. None if not on disk yet."""
    hits = sorted(d for d in DAYS.glob(f"day-{n:02d}-*") if d.is_dir())
    return hits[0] if hits else None


def state(n: int) -> str:
    d = day_dir(n)
    if d is None or not (d / "LESSON.md").exists():
        return "unwritten"
    checklist = d / "CHECKLIST.md"
    if checklist.exists() and not re.search(r"^- \[ \]", checklist.read_text(), re.MULTILINE):
        return "done"
    return "written"


MARK = {"done": "✅", "written": "📝", "unwritten": "·"}


def render() -> str:
    rows = parse_index()
    seen = {r["day"]: state(r["day"]) for r in rows}
    done = sum(1 for s in seen.values() if s == "done")
    written = sum(1 for s in seen.values() if s in {"done", "written"})
    total = len(rows)

    lines = [
        "# Tracker",
        "",
        "<!-- GENERATED by scripts/tracker.py — do not hand-edit. -->",
        f"_Regenerated {date.today().isoformat()}._",
        "",
        f"**{done} / {total} days complete** · {written} written · "
        f"{total - written} not yet written",
        "",
        "✅ complete (checklist fully ticked) · 📝 written, not finished · · not yet written",
        "",
    ]

    current = object()
    for r in rows:
        if r["phase"] != current:
            current = r["phase"]
            lines += ["", f"### Phase {r['phase']} — {r['phase_title']}", ""]
            lines += ["| | Day | Title | IDs |", "|---|---:|---|---|"]
        gate = " 🔒" if r["gate"] else ""
        lines.append(
            f"| {MARK[seen[r['day']]]} | {r['day']}{gate} | {r['title']} | "
            f"{' · '.join(f'`{i}`' for i in r['ids']) or '—'} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = sys.argv[1:]
    text = render()
    if "--write" in args:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)}")
    else:
        head = [ln for ln in text.splitlines() if ln.startswith("**")]
        print(head[0] if head else text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
