"""Project the written lessons into a small index the writer can afford to read.

The problem this solves: before writing day N you must know what the reader already
knows. The lessons that carry that knowledge run to 30 KB each, and there are two per
day. By day 100 you cannot read them. This file compiles them into three small
documents instead.

Nothing here is generated, summarised or paraphrased. Every byte written is copied
verbatim from a lesson, and every entry carries the path it came from. If a claim is
wrong, the lesson is wrong.

    python scripts/wiki.py          # regenerate wiki/
    python scripts/wiki.py --lint   # report what is stale, write nothing

Three files come out:

    wiki/00-STATE.md          one row per written day, both tracks
    wiki/vocab.md             every term the reader has met, and the day it arrived
    wiki/recall/<phase>.md    section 9 of each lesson in that phase, verbatim

Read 00-STATE.md and vocab.md always. Read only the two recall files for the phases
the day sits in. That is the whole saving.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DAYS_DIR = ROOT / "days"
WIKI_DIR = ROOT / "wiki"

FRONT_MATTER = re.compile(r"^---\n(.*?)\n---", re.S)
BOLD = re.compile(r"\*\*([^*\n]{3,40})\*\*")

# A term is being defined, not merely emphasised, when a copula or a dash follows it.
DEFINITION = re.compile(r"\*\*[^*\n]{3,40}\*\*\s*(?:is|are|means|\u2014|\u2013|-|:)\s")

# Ordinary English that turns up in bold for emphasis. Bold alone is not a definition.
STOPWORDS = frozenset(
    """a an the and or but if then this that there here it is are was be do does have has
    of in on at to for from with by as up out over under all any each more most some such
    no not only same so too very can will just now above below back when where what which
    about into through also however therefore still yet even ever never often work thing
    way point case part kind example answer question problem idea rule step line order
    place store time accept refuse reason report average random group""".split()
)


@dataclass(frozen=True)
class WrittenLesson:
    """One lesson file that is finished, with the front matter it declares."""

    day: int
    track: str
    title: str
    phase: str
    path: str
    text: str


def _front_matter(text: str) -> dict[str, str]:
    match = FRONT_MATTER.match(text)
    if not match:
        return {}
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fields[key.strip()] = value.strip().strip('"')
    return fields


def section(text: str, number: int) -> str:
    """The body under '## <number>. ...', up to the next '## '. Verbatim."""
    match = re.search(rf"^## {number}\.\s*.+$", text, re.M)
    if not match:
        return ""
    rest = text[match.end() :]
    following = re.search(r"^## ", rest, re.M)
    body = rest[: following.start()] if following else rest
    return body.strip()


def load_written() -> list[WrittenLesson]:
    """Every lesson whose front matter says it is written, in day order."""
    lessons: list[WrittenLesson] = []
    for path in sorted(DAYS_DIR.glob("day-*/0[12]-*.md")):
        text = path.read_text(encoding="utf-8")
        fields = _front_matter(text)
        if fields.get("status") != "written":
            continue
        lessons.append(
            WrittenLesson(
                day=int(fields["day"]),
                track=fields.get("track", "?"),
                title=fields.get("title", "?"),
                phase=fields.get("phase", "?"),
                path=path.relative_to(ROOT).as_posix(),
                text=text,
            )
        )
    return sorted(lessons, key=lambda lesson: (lesson.day, lesson.track))


def phase_slug(phase: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", phase.lower()).strip("-")


GENERATED = "<!-- generated by scripts/wiki.py — do not hand-edit, run ./k wiki -->"


def looks_like_a_term(raw: str) -> bool:
    """True when a bold span is a term being named, not a phrase being stressed.

    Tuned for precision over recall on purpose. A term this filter misses costs you a
    needless re-definition. A term it wrongly admits costs the reader a word they have
    never met, which is the failure the vocabulary ledger exists to prevent.
    """
    term = raw.strip()
    if term.endswith((".", ",", ":", "!", "?")) or "`" in term or term.startswith("_"):
        return False
    words = term.split()
    if not 1 <= len(words) <= 3:
        return False
    if term.isupper():
        return True  # ACID, TCP, CAP — acronyms are always terms
    if term[0].isupper():
        return False  # "Jump straight there" — a stressed sentence fragment
    if all(word.lower() in STOPWORDS for word in words):
        return False
    return all(word.replace("-", "").replace("/", "").isalpha() for word in words)


def first_definitions(lessons: list[WrittenLesson]) -> dict[str, int]:
    """Every term the reader has met, mapped to the day it first appeared."""
    first: dict[str, int] = {}
    for lesson in lessons:
        for line in section(lesson.text, 3).splitlines():
            if not DEFINITION.search(line):
                continue
            for raw in BOLD.findall(line):
                term = raw.strip().lower()
                if looks_like_a_term(raw) and term not in first:
                    first[term] = lesson.day
    return first


def write_state(lessons: list[WrittenLesson]) -> Path:
    by_day: dict[int, dict[str, WrittenLesson]] = defaultdict(dict)
    for lesson in lessons:
        by_day[lesson.day][lesson.track] = lesson

    lines = [
        "# Krama — what has actually been written",
        "",
        GENERATED,
        "",
        "One row per day whose lessons are finished. Titles are copied from each lesson's",
        "front matter. A day that is missing from this table has not been written yet.",
        "",
        "| Day | DSA lesson | System design lesson |",
        "|---:|---|---|",
    ]
    for day in sorted(by_day):
        tracks = by_day[day]
        dsa = tracks["dsa"].title if "dsa" in tracks else "—"
        sd = tracks["system-design"].title if "system-design" in tracks else "—"
        lines += [f"| {day:03d} | {dsa} | {sd} |"]
    lines += ["", f"**{len(by_day)} of 180 days written.**", ""]

    path = WIKI_DIR / "00-STATE.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_vocab(lessons: list[WrittenLesson]) -> Path:
    by_day: dict[int, list[str]] = defaultdict(list)
    for term, day in sorted(first_definitions(lessons).items()):
        by_day[day].append(term)

    lines = [
        "# Vocabulary — every term the reader has already met",
        "",
        GENERATED,
        "",
        "Bold spans from section 3 of each written lesson, kept when the line defines the",
        "term rather than stresses it, and dated to the day it first appeared. Copied",
        "verbatim. To find one: `grep -rn '**term**' days/day-NNN-*`.",
        "",
        "**You may use any term below, and link to the day it arrived. A term that is not",
        "here is a term the reader has never seen — define it, or drop it.**",
        "",
        "This list prefers precision to completeness. If a term you need is missing, it is",
        "cheaper to define it again than to assume the reader knows it.",
        "",
    ]
    lines += [f"- **{day:03d}** — " + ", ".join(by_day[day]) for day in sorted(by_day)]
    lines += [""]

    path = WIKI_DIR / "vocab.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# A recall card links to sibling days as ../day-NNN-slug/. Copied into wiki/recall/ that
# path no longer resolves, so rewrite it. The link text is untouched.
DAY_LINK = re.compile(r"\]\(\.\./(day-\d{3}-)")


def relocate_links(card: str) -> str:
    """Repoint a card's relative day links now that it lives two folders deeper."""
    return DAY_LINK.sub(r"](../../days/\1", card)


def write_recall(lessons: list[WrittenLesson]) -> list[Path]:
    by_phase: dict[str, list[WrittenLesson]] = defaultdict(list)
    for lesson in lessons:
        by_phase[lesson.phase].append(lesson)

    written: list[Path] = []
    for phase, group in sorted(by_phase.items()):
        lines = [
            f"# Recall cards — {phase}",
            "",
            GENERATED,
            "",
            "Section 9 of every finished lesson in this phase, copied verbatim. This is what",
            "the reader can already recall. Use these ideas freely and link to the day.",
            "",
        ]
        for lesson in group:
            card = relocate_links(section(lesson.text, 9)) or "_(no recall card)_"
            lines += [
                f"## Day {lesson.day:03d} · {lesson.track} — {lesson.title}",
                "",
                f"Source: [`{lesson.path}`](../../{lesson.path})",
                "",
                card,
                "",
            ]
        path = WIKI_DIR / "recall" / f"{phase_slug(phase)}.md"
        path.write_text("\n".join(lines), encoding="utf-8")
        written.append(path)
    return written


def build() -> list[Path]:
    """Regenerate every wiki file. Returns what was written."""
    lessons = load_written()
    (WIKI_DIR / "recall").mkdir(parents=True, exist_ok=True)
    for stale in (WIKI_DIR / "recall").glob("*.md"):
        stale.unlink()
    return [write_state(lessons), write_vocab(lessons), *write_recall(lessons)]


def lint() -> list[str]:
    """Report where the wiki has drifted from the lessons. Writes nothing."""
    problems: list[str] = []
    lessons = load_written()

    state = WIKI_DIR / "00-STATE.md"
    if not state.exists():
        return ["wiki/ has never been built — run ./k wiki"]

    on_disk = state.read_text(encoding="utf-8")
    for day in sorted({lesson.day for lesson in lessons}):
        if f"| {day:03d} |" not in on_disk:
            problems.append(f"wiki/00-STATE.md: day {day:03d} is written but missing")

    phases = {phase_slug(lesson.phase) for lesson in lessons}
    for phase in sorted(phases):
        if not (WIKI_DIR / "recall" / f"{phase}.md").exists():
            problems.append(f"wiki/recall/{phase}.md: missing")
    for orphan in sorted((WIKI_DIR / "recall").glob("*.md")):
        if orphan.stem not in phases:
            problems.append(f"wiki/recall/{orphan.name}: no written lesson in that phase")

    newest = max((Path(ROOT / lesson.path).stat().st_mtime for lesson in lessons), default=0)
    if newest > state.stat().st_mtime:
        problems.append("wiki/ is older than the newest lesson — run ./k wiki")

    return problems


def main() -> int:
    if "--lint" in sys.argv[1:]:
        problems = lint()
        for problem in problems:
            print(f"  · {problem}")
        print(f"\nwiki: {len(problems)} problem(s)")
        return 1 if problems else 0

    written = build()
    total = sum(path.stat().st_size for path in written)
    for path in written:
        print(f"  {path.stat().st_size:>7,} B  {path.relative_to(ROOT).as_posix()}")
    print(f"\n{len(written)} files · {total:,} B · ~{total // 4:,} tokens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
