"""Days 106-180: mastery, big projects, and the capstone.

106-135  idiomatic depth, design, and the standard libraries
136-165  six five-day builds
166-180  interview prep and the capstone

Row shape: (n, slug, theme, py_title, go_title, cpp_title, outcome, ask)
"""

# fmt: off
DAYS = [
 # ---------------- 4a: Idiomatic depth (106-135) ----------------
 (106, "data-modelling-idioms", "Data modelling idioms",
  "dataclasses, attrs, pydantic, and when each",
  "Struct tags, validation, and functional options",
  "Aggregates, designated initialisers, and builder structs",
  "You can model a config or a record idiomatically in each language, with validation.",
  "How do you validate a struct on construction?"),

 (107, "cleanup-idioms", "Cleanup: context managers, defer, RAII",
  "with, __enter__/__exit__, and contextlib",
  "defer, its evaluation order, and the loop trap",
  "RAII, scope guards, and destructors that never throw",
  "You can guarantee a file closes or a lock releases on every path, in each language.",
  "How do you make sure a resource is released even if the code throws?"),

 (108, "properties-and-encapsulation", "Encapsulation",
  "@property, __slots__, name mangling, and descriptors",
  "Unexported fields, getters by convention, and method values",
  "private, const methods, static members, and friend",
  "You can hide a field and expose a computed one in each language.",
  "When would you use a getter instead of a public field?"),

 (109, "static-typing-deep", "Static typing, deep",
  "mypy strict, Protocol, TypeVar bounds, and overload",
  "Generic constraints, type sets, and interface embedding",
  "Concepts, requires clauses, and constrained auto",
  "You can express 'any type with a Len method' in each language and get a compile-time error when it is wrong.",
  "How do you constrain a generic type?"),

 (110, "async-deep", "Async, deep",
  "TaskGroup, semaphores, cancellation, and aiohttp",
  "errgroup, sync.Once, semaphores, and singleflight",
  "Futures, promises, and a coroutine task type",
  "You can run bounded concurrent work with error propagation in each language.",
  "Ten calls are in flight and one fails. What happens to the other nine?"),

 (111, "parallelism-and-the-scheduler", "Parallelism and the scheduler",
  "multiprocessing, the GIL, and free-threaded Python",
  "GOMAXPROCS, the M:P:G scheduler, and preemption",
  "std::execution policies and hardware_concurrency",
  "You can use every core in each language and say what stops you from doing so.",
  "How many goroutines can you run on one core?"),

 (112, "stdlib-tour-algorithms", "Standard library tour I: algorithms",
  "itertools, functools, bisect, and heapq",
  "slices, maps, sort, and container/heap",
  "<algorithm>, <ranges>, <numeric>",
  "You can reach for the standard function instead of writing the loop, in each language.",
  "How would you find the k largest items?"),

 (113, "stdlib-tour-containers", "Standard library tour II: containers",
  "collections: deque, Counter, defaultdict, OrderedDict",
  "container/list, container/ring, and why maps and slices win",
  "deque, list, set, priority_queue, and unordered containers",
  "You can choose the right container by the operation you need, in each language.",
  "Which container would you use for an LRU cache?"),

 (114, "stdlib-tour-strings", "Standard library tour III: text",
  "str methods, textwrap, string.Template, and difflib",
  "strings, strconv, unicode, and text/tabwriter",
  "std::string, std::string_view, std::format, and <charconv>",
  "You can parse, transform, and format text without a third-party library, in each language.",
  "How do you convert a string to an integer safely?"),

 (115, "publishing-a-library", "Publishing a library",
  "PyPI, versioning, and a clean public API",
  "Module proxy, semantic import versioning, and v2 paths",
  "vcpkg or Conan, a CMake package config, and an install target",
  "You can publish a library someone else can install, in each language.",
  "How do you version a library without breaking users?"),

 (116, "documentation", "Documentation",
  "Docstrings, Sphinx or mkdocs, and doctest",
  "godoc conventions, examples that run as tests",
  "Doxygen and a README that builds",
  "You can document a package so a stranger can use it, in each language.",
  "What belongs in a README?"),

 (117, "linting-and-static-analysis", "Linting and static analysis",
  "ruff, mypy, and pre-commit",
  "vet, staticcheck, golangci-lint",
  "clang-tidy, cppcheck, and warnings as errors",
  "You can make the tools catch a real bug before a human reads the code, in each language.",
  "What does a linter catch that tests do not?"),

 (118, "fuzzing", "Fuzz testing",
  "hypothesis for property-based tests",
  "go test -fuzz and the corpus",
  "libFuzzer with sanitizers",
  "You can let the computer find the input that breaks your parser, in each language.",
  "How would you test a parser against inputs you did not think of?"),

 (119, "test-strategy", "Test strategy",
  "Unit, integration, and end-to-end with pytest markers",
  "Unit, integration with build tags, and end-to-end",
  "Unit, integration, and end-to-end with CTest labels",
  "You can say what to test at which level, and keep the suite fast, in each language.",
  "What is the testing pyramid and where does most of your time go?"),

 (120, "project-8-rate-limiter-library", "Mini project 8: a rate-limiter library",
  "A published Python package with docs and tests",
  "A published Go module with docs and tests",
  "A C++ library with a CMake package and tests",
  "You can ship a small, correct, documented library in all three languages.",
  "Show me a library you wrote. How would I use it?"),

 (121, "patterns-creational", "Design patterns I: strategy, factory, builder",
  "Strategy as functions, factories as classmethods, builders as kwargs",
  "Strategy as interfaces, factory functions, functional options",
  "Strategy with virtual or templates, factories, fluent builders",
  "You can implement the three most-asked creational patterns idiomatically in each language.",
  "Implement the builder pattern. Now say why Python rarely needs it."),

 (122, "patterns-structural", "Design patterns II: observer, decorator, adapter",
  "Observer with callbacks, decorator as wrapper, adapter as class",
  "Observer with channels, decorator as wrapping interface, adapter",
  "Observer with std::function, decorator, adapter",
  "You can implement the three most-asked structural patterns idiomatically in each language.",
  "How would you notify five parts of the program when a value changes?"),

 (123, "patterns-behavioural", "Design patterns III: singleton, state, command",
  "Module-level singletons, state as enum plus match, command as callable",
  "sync.Once, state as interface, command as func",
  "Meyers singleton, state as variant, command as std::function",
  "You can implement the three most-asked behavioural patterns and say when a singleton is a mistake.",
  "Implement a singleton. Now tell me why you should not."),

 (124, "functional-style", "Functional style",
  "map, filter, reduce, comprehensions, and pure functions",
  "Higher-order functions, and why Go keeps it plain",
  "Ranges, views, and pure functions",
  "You can write a data transformation as a pipeline of pure functions in each language.",
  "What is a pure function, and why does it matter for testing?"),

 (125, "dependency-injection", "Dependency injection",
  "Constructor injection with Protocols, and pytest fixtures",
  "Constructor injection with interfaces, and wire in outline",
  "Constructor injection with interfaces, and templates",
  "You can swap a real database for a fake in a test without a framework, in each language.",
  "How do you test code that talks to a database?"),

 (126, "clean-architecture", "Clean architecture",
  "Domain, application, infrastructure layers in a Python service",
  "Domain, application, infrastructure layers in a Go service",
  "Domain, application, infrastructure layers in a C++ service",
  "You can lay out a service so the business rules never import the database, in each language.",
  "How do you structure a service so the framework can be swapped?"),

 (127, "error-architecture", "Error architecture",
  "A domain exception hierarchy mapped to HTTP codes",
  "Typed errors, sentinel errors, and mapping to gRPC codes",
  "std::expected with a domain error enum, mapped to codes",
  "You can design how errors flow from the database to the user, in each language.",
  "A row is missing. What does the user see, and how did it get there?"),

 (128, "twelve-factor", "Twelve-factor services",
  "Config, logs to stdout, stateless processes, in Python",
  "Config, logs to stdout, stateless processes, in Go",
  "Config, logs to stdout, stateless processes, in C++",
  "You can name the twelve factors and point at where each of your services obeys them.",
  "Why should a service write logs to stdout?"),

 (129, "security-basics", "Security basics",
  "Input validation, injection, secrets, and pickle",
  "Input validation, injection, secrets, and the crypto packages",
  "Bounds checking, undefined behaviour, and the sanitizers",
  "You can name the top five ways each language gets exploited and how you prevent each.",
  "What is undefined behaviour, and why does it matter?"),

 (130, "reading-idiomatic-code", "Reading idiomatic code",
  "A tour of a well-written Python package",
  "A tour of a well-written Go package from the standard library",
  "A tour of a well-written C++ library",
  "You can read a real codebase in each language and say what is idiomatic and what is not.",
  "What does idiomatic mean in your language?"),

 (131, "go-deep-channel-patterns", "Go, deep: channel patterns",
  "The same patterns with asyncio queues",
  "Done channels, fan-in, fan-out, select with default, and time.After",
  "The same patterns with condition variables",
  "You can write the five classic Go concurrency patterns from memory and explain each with a diagram.",
  "How do you stop a goroutine?"),

 (132, "cpp-deep-templates-and-constexpr", "C++, deep: templates and constexpr",
  "The nearest Python idea: generics and runtime dispatch",
  "The nearest Go idea: generics and code generation",
  "Templates, CRTP, concepts, constexpr, and compile-time tables",
  "You can write a compile-time lookup table and a CRTP base class, and say what each buys.",
  "What is CRTP, and why would you use it?"),

 (133, "python-deep-object-model", "Python, deep: the object model",
  "Descriptors, metaclasses, __new__, and the import system",
  "The nearest Go idea: reflection and struct tags",
  "The nearest C++ idea: templates and traits",
  "You can explain how a dataclass or an ORM works underneath, and write a tiny one.",
  "What is a metaclass, and have you ever needed one?"),

 (134, "same-program-three-languages", "One program, three languages, measured",
  "A JSON log parser in Python, profiled",
  "A JSON log parser in Go, profiled",
  "A JSON log parser in C++, profiled",
  "You can show the same task at three speeds and explain every gap with a profile.",
  "Why is the Go version 20 times faster than Python here?"),

 (135, "project-9-kv-store", "Mini project 9: a key-value store with a wire protocol",
  "A KV server and client in Python",
  "A KV server and client in Go",
  "A KV server and client in C++",
  "You can design a small binary protocol and ship a server and client for it in all three.",
  "Design a protocol for a key-value store."),

 # ---------------- 4b: Six five-day builds (136-165) ----------------
 (136, "build-a-cache-1-design", "Build A, day 1: a distributed cache. Design",
  "Requirements and the Python client interface",
  "Requirements, the .proto API, and the Go server skeleton",
  "Requirements and the C++ client interface",
  "You can write the requirements and the protobuf API for a distributed cache.",
  "Design a distributed cache. Start with the API."),

 (137, "build-a-cache-2-server", "Build A, day 2: the server core",
  "Property tests against the server",
  "Sharded maps, TTLs, eviction, and the gRPC service",
  "A load generator",
  "You can implement an LRU-with-TTL store behind a gRPC service in Go.",
  "How do you evict from a cache under memory pressure?"),

 (138, "build-a-cache-3-clients", "Build A, day 3: clients",
  "A Python client with connection pooling and retries",
  "A Go client library",
  "A C++ client with connection pooling and retries",
  "You can write a client library in each language against the same protobuf API.",
  "What does a good client library do for you?"),

 (139, "build-a-cache-4-hashing", "Build A, day 4: consistent hashing",
  "Consistent hashing simulation in Python",
  "A hash ring and node add/remove in Go",
  "The hash ring in C++",
  "You can spread keys over N nodes so adding one moves only 1/N of them.",
  "What happens to the keys when you add a cache node?"),

 (140, "build-a-cache-5-ship", "Build A, day 5: ship it",
  "Docs and a demo notebook",
  "Docker, metrics, and CI",
  "Benchmarks",
  "You can ship the cache with docs, metrics, containers, and a README a stranger could use.",
  "Walk me through a system you built end to end."),

 (141, "build-b-jobs-1-design", "Build B, day 1: a job queue. Design",
  "Requirements and the FastAPI submit/status API",
  "Requirements, the .proto job schema, and the Go worker skeleton",
  "Requirements and the C++ compute worker skeleton",
  "You can design a job system with a submit API, a queue, workers, and status.",
  "Design a background job system."),

 (142, "build-b-jobs-2-queue", "Build B, day 2: the queue and the worker",
  "Submit, poll, and cancel from Python",
  "Redis Streams or Kafka, the worker loop, and acknowledgements",
  "The C++ worker consuming protobuf jobs",
  "You can implement at-least-once delivery with acknowledgements and visibility timeouts.",
  "What happens if a worker dies mid-job?"),

 (143, "build-b-jobs-3-retries", "Build B, day 3: retries and dead letters",
  "Retry policy in the API",
  "Exponential backoff, dead-letter queue, and poison messages",
  "Idempotent compute in C++",
  "You can retry failed jobs safely and quarantine the ones that will never succeed.",
  "What is a poison message?"),

 (144, "build-b-jobs-4-scheduling", "Build B, day 4: scheduling and priorities",
  "Cron-style scheduling from Python",
  "Priority queues, delayed jobs, and a scheduler loop",
  "Priority handling in the C++ worker",
  "You can schedule a job for later and run urgent ones first.",
  "How do you run a job at a specific time in a distributed system?"),

 (145, "build-b-jobs-5-ship", "Build B, day 5: ship it",
  "A dashboard page",
  "Metrics, graceful shutdown, and CI",
  "Benchmarks",
  "You can ship the job system with a dashboard, metrics, and CI.",
  "How do you know your job system is healthy?"),

 (146, "build-c-storage-1-design", "Build C, day 1: a storage engine. Design",
  "Python bindings plan",
  "Go bindings plan",
  "Requirements, the on-disk format, and the C++ engine skeleton",
  "You can design a log-structured storage engine and its file format.",
  "How does a database store data on disk?"),

 (147, "build-c-storage-2-wal-and-memtable", "Build C, day 2: WAL and memtable",
  "A pure-Python reference implementation for testing",
  "A pure-Go reference implementation for testing",
  "Write-ahead log, fsync, and a sorted in-memory table",
  "You can make writes durable and explain what fsync guarantees.",
  "What is a write-ahead log for?"),

 (148, "build-c-storage-3-sstables", "Build C, day 3: SSTables and compaction",
  "Reading SSTables from Python",
  "Reading SSTables from Go",
  "Flushing, sorted files, bloom filters, and compaction",
  "You can flush the memtable to disk and merge files without losing data.",
  "What is compaction, and why is it needed?"),

 (149, "build-c-storage-4-bindings", "Build C, day 4: bindings",
  "pybind11 bindings and a Python API",
  "cgo bindings and a Go API",
  "extern C surface and a stable ABI",
  "You can call the C++ engine from Python and Go.",
  "How do you expose a C++ library to other languages?"),

 (150, "build-c-storage-5-ship", "Build C, day 5: ship it",
  "Tests through the bindings",
  "Tests through the bindings",
  "Crash tests, benchmarks, and docs",
  "You can prove the engine survives a crash and ship it with benchmarks.",
  "How would you test that a database survives a power cut?"),

 (151, "build-d-chat-1-design", "Build D, day 1: a chat system. Design",
  "Requirements and the web client plan",
  "Requirements, the .proto messages, and the Go hub",
  "Requirements and the C++ presence service",
  "You can design a chat system with rooms, presence, and history.",
  "Design a chat application."),

 (152, "build-d-chat-2-streams", "Build D, day 2: gRPC bidirectional streams",
  "A Python terminal client on the stream",
  "The room hub with bidirectional streaming",
  "A C++ terminal client on the stream",
  "You can hold thousands of open streams and fan a message out to a room.",
  "How do you push a message to everyone in a room?"),

 (153, "build-d-chat-3-websockets", "Build D, day 3: WebSockets for the browser",
  "A FastAPI WebSocket gateway to the gRPC hub",
  "WebSocket to gRPC bridging",
  "Presence updates over gRPC",
  "You can bridge a browser to the gRPC hub.",
  "The browser cannot open a gRPC stream. What do you do?"),

 (154, "build-d-chat-4-history-and-presence", "Build D, day 4: history and presence",
  "History queries",
  "Postgres history, cursor pagination, and Redis presence",
  "The presence service with heartbeats",
  "You can page through history and know who is online.",
  "How do you know a user went offline?"),

 (155, "build-d-chat-5-ship", "Build D, day 5: ship it",
  "Load test with locust",
  "Metrics, tracing, and CI",
  "Benchmarks",
  "You can ship the chat system and show a trace of one message end to end.",
  "Show me one message travelling through your system."),

 (156, "build-e-observability-1-design", "Build E, day 1: an observability toolkit. Design",
  "Requirements and the dashboard plan",
  "Requirements, the .proto metrics schema, and the Go agent",
  "Requirements and the C++ collector skeleton",
  "You can design a metrics agent, a collector, and a dashboard.",
  "Design a monitoring system."),

 (157, "build-e-observability-2-agent", "Build E, day 2: the agent",
  "A Python client library for custom metrics",
  "Collecting CPU, memory, and app metrics; shipping over gRPC",
  "Receiving and buffering in C++",
  "You can collect and ship metrics from a host every ten seconds.",
  "How does a metrics agent avoid overloading the collector?"),

 (158, "build-e-observability-3-storage", "Build E, day 3: time-series storage",
  "Querying from Python",
  "Batching and forwarding",
  "A columnar time-series store with downsampling",
  "You can store a million points a minute and query a day in milliseconds.",
  "How would you store time-series data?"),

 (159, "build-e-observability-4-dashboard", "Build E, day 4: the dashboard and alerts",
  "A FastAPI dashboard and an alert evaluator",
  "Alert rules and notification fan-out",
  "Query API in C++",
  "You can draw a graph and fire an alert on a threshold.",
  "How do you avoid alert fatigue?"),

 (160, "build-e-observability-5-ship", "Build E, day 5: ship it",
  "Docs and demo",
  "CI and containers",
  "Benchmarks",
  "You can ship the toolkit and monitor your own earlier projects with it.",
  "What would you monitor first in a new service?"),

 (161, "build-f-interpreter-1-lexer", "Build F, day 1: a tiny language. The lexer",
  "The lexer in Python",
  "The lexer in Go",
  "The lexer in C++",
  "You can turn source text into tokens in each language.",
  "What does a lexer do?"),

 (162, "build-f-interpreter-2-parser", "Build F, day 2: the parser",
  "A recursive-descent parser in Python",
  "A recursive-descent parser in Go",
  "A recursive-descent parser in C++",
  "You can turn tokens into a tree with correct precedence, in each language.",
  "How does a parser handle operator precedence?"),

 (163, "build-f-interpreter-3-evaluator", "Build F, day 3: the evaluator",
  "A tree-walking evaluator with environments",
  "A tree-walking evaluator with environments",
  "A tree-walking evaluator with std::variant values",
  "You can run programs in your language, with variables, functions, and closures.",
  "How do closures capture variables in an interpreter?"),

 (164, "build-f-interpreter-4-errors-and-tests", "Build F, day 4: errors and tests",
  "Error messages with line numbers, and a test suite",
  "Error messages with line numbers, and a test suite",
  "Error messages with line numbers, and a test suite",
  "You can report a syntax error a human can act on, and prove the interpreter with tests.",
  "How do you produce a good error message from a parser?"),

 (165, "build-f-interpreter-5-ship", "Build F, day 5: ship it",
  "A REPL and docs",
  "A REPL and docs",
  "A REPL, benchmarks, and docs",
  "You can ship an interpreter in three languages and compare their speed.",
  "Which of your three interpreters is fastest, and why?"),

 # ---------------- 4c: Interview prep and capstone (166-180) ----------------
 (166, "python-interview-questions", "Python interview questions",
  "The forty questions: GIL, memory, decorators, generators, typing",
  "How Go answers the same questions",
  "How C++ answers the same questions",
  "You can answer the forty most-asked Python questions out loud.",
  "What is the GIL, and when does it matter?"),

 (167, "go-interview-questions", "Go interview questions",
  "How Python answers the same questions",
  "The forty questions: goroutines, channels, interfaces, nil, slices, GC",
  "How C++ answers the same questions",
  "You can answer the forty most-asked Go questions out loud.",
  "Why can a nil pointer inside an interface be non-nil?"),

 (168, "cpp-interview-questions", "C++ interview questions",
  "How Python answers the same questions",
  "How Go answers the same questions",
  "The forty questions: virtual, smart pointers, move, RAII, UB, templates",
  "You can answer the forty most-asked C++ questions out loud.",
  "What is the rule of five?"),

 (169, "choosing-a-language", "Choosing a language",
  "When Python: the honest case",
  "When Go: the honest case",
  "When C++: the honest case",
  "You can pick a language for a given job and defend it in two minutes.",
  "Which language would you use for this service, and why?"),

 (170, "reading-production-code", "Reading production code",
  "A guided read of a popular Python service codebase",
  "A guided read of a popular Go service codebase",
  "A guided read of a popular C++ library",
  "You can open a large unfamiliar codebase in each language and find where a request is handled.",
  "You join a team with a 200k-line codebase. Day one, what do you do?"),

 (171, "capstone-1-requirements", "Capstone, day 1: an order platform. Requirements and API",
  "The FastAPI gateway contract",
  "The protobuf APIs for orders, inventory, and payments",
  "The C++ pricing engine contract",
  "You can write the requirements and every API of the capstone before writing a line of logic.",
  "Design an e-commerce order platform."),

 (172, "capstone-2-gateway", "Capstone, day 2: the gateway",
  "FastAPI gateway: auth, validation, and gRPC calls",
  "Gateway middleware for auth tokens",
  "Nothing today; C++ waits for pricing",
  "You can accept a request at the edge, validate it, and forward it over gRPC.",
  "What belongs in an API gateway?"),

 (173, "capstone-3-order-service", "Capstone, day 3: the order service",
  "Contract tests from Python",
  "Order service: Postgres, transactions, and the outbox",
  "Contract tests from C++",
  "You can create an order atomically with an event that will definitely be published.",
  "How do you guarantee the order event is published exactly once?"),

 (174, "capstone-4-pricing-engine", "Capstone, day 4: the pricing engine",
  "Price rules loaded from Python tooling",
  "Calling pricing over gRPC with deadlines",
  "The C++ pricing engine: rules, discounts, and sub-millisecond latency",
  "You can build a service that answers in under a millisecond and prove it.",
  "Why is this service in C++?"),

 (175, "capstone-5-events-and-workers", "Capstone, day 5: events and workers",
  "Notification and analytics workers on Kafka",
  "Inventory worker with idempotent consumption",
  "Nothing today; C++ is done",
  "You can react to an order event in two services without double-processing.",
  "What happens if the notification worker receives the same event twice?"),

 (176, "capstone-6-resilience", "Capstone, day 6: resilience",
  "Timeouts, retries, and a circuit breaker in the gateway",
  "Deadlines, retries, and idempotency keys across services",
  "Load shedding in the pricing engine",
  "You can kill any one service and show the platform degrade instead of fall over.",
  "Kill the pricing service. What does the user see?"),

 (177, "capstone-7-observability-and-deploy", "Capstone, day 7: observe and deploy",
  "Tracing through the gateway",
  "Tracing across gRPC and Kafka; Kubernetes manifests",
  "Metrics from the engine",
  "You can deploy the whole platform to a local cluster and follow one order through a trace.",
  "Show me one order travelling through your system."),

 (178, "capstone-8-load-and-review", "Capstone, day 8: load test and review",
  "Load test with locust and a report",
  "Profile under load and fix the top hotspot",
  "Profile under load and fix the top hotspot",
  "You can state the platform's throughput and latency and what you fixed to get there.",
  "What is your p99 latency, and what limits it?"),

 (179, "portfolio-and-presenting", "Your portfolio",
  "READMEs, demos, and the two-minute pitch for each project",
  "READMEs, demos, and the two-minute pitch for each project",
  "READMEs, demos, and the two-minute pitch for each project",
  "You can present any of your ten projects in two minutes and answer questions for ten.",
  "Tell me about a project you are proud of."),

 (180, "final-revision", "Final revision",
  "The hundred questions, Python",
  "The hundred questions, Go",
  "The hundred questions, C++",
  "You can answer the hundred questions across the three languages out loud, from memory.",
  "Tell me about the three languages you know."),
]
