"""Days 46-105: applied programming.

46-60   networking, HTTP, databases, and a REST API
61-75   Protocol Buffers and gRPC, Go first, Python and C++ as clients
76-90   performance, systems programming, and interop
91-105  messaging, resilience, observability, and deployment

Row shape: (n, slug, theme, py_title, go_title, cpp_title, outcome, ask)
"""

# fmt: off
DAYS = [
 # ---------------- 3a: Networking, HTTP, data (46-60) ----------------
 (46, "tcp-sockets", "TCP sockets: an echo server",
  "socket, bind, listen, accept, and a threaded echo server",
  "net.Listen, Accept, and one goroutine per connection",
  "POSIX sockets, or Boost.Asio, and one thread per connection",
  "You can write a server that accepts a connection and echoes bytes back, in each language, and test it with a client.",
  "What happens when a client connects to your server?"),

 (47, "http-client", "HTTP clients",
  "httpx and requests: GET, POST, headers, timeouts, sessions",
  "net/http Client, requests, headers, and reusing the transport",
  "libcurl through cpr: GET, POST, headers, timeouts",
  "You can call a JSON API with a timeout in each language and handle a 500.",
  "What goes wrong if you create a new HTTP client for every request?"),

 (48, "http-server", "HTTP servers",
  "FastAPI: a route, a request model, a response model",
  "net/http: ServeMux, handlers, and http.ListenAndServe",
  "cpp-httplib: routes and handlers",
  "You can serve a JSON endpoint on a port in each language and hit it with curl.",
  "Walk me through how your server handles one request."),

 (49, "routing-and-middleware", "Routing and middleware",
  "Routers, path parameters, dependencies, and middleware in FastAPI",
  "Method and path patterns in ServeMux, and a middleware chain",
  "Route patterns, pre-routing handlers, and a logging wrapper",
  "You can add authentication and logging to every route without repeating code, in each language.",
  "How would you add request logging to every endpoint?"),

 (50, "json-apis", "Designing a JSON API",
  "Pydantic models, validation errors, and status codes",
  "Decoding request bodies, validation, and writing error responses",
  "Parsing request bodies, validation, and consistent error shapes",
  "You can build a CRUD endpoint set with proper status codes and error bodies, in each language.",
  "What should a 400 response body look like?"),

 (51, "cli-args-config-env", "Configuration: flags, environment, files",
  "argparse and typer, os.environ, and a settings class",
  "flag, cobra, os.Getenv, and a Config struct",
  "CLI11, getenv, and a Config struct",
  "You can configure a program from flags, env vars and a file, with a clear precedence order, in each language.",
  "Where should a database password come from, and where should it never be?"),

 (52, "logging", "Logging that helps at 3am",
  "logging, structlog, levels, and JSON output",
  "log/slog: structured, levelled, and with context",
  "spdlog: sinks, levels, and formatting",
  "You can emit structured logs with request IDs in each language and grep them.",
  "What do you log, and what must you never log?"),

 (53, "sqlite", "Databases I: SQLite",
  "sqlite3: connect, execute, parameters, and transactions",
  "database/sql with modernc sqlite, prepared statements, and Scan",
  "SQLite C API and a thin RAII wrapper",
  "You can create a table, insert, query and update from each language, safely with parameters.",
  "What is SQL injection, and how do parameters stop it?"),

 (54, "postgres-and-pools", "Databases II: Postgres and connection pools",
  "psycopg 3 and asyncpg, and a connection pool",
  "pgx, pgxpool, and context-aware queries",
  "libpqxx: connections, transactions, and prepared statements",
  "You can talk to a real Postgres from each language and say why a pool exists.",
  "Why do you need a connection pool?"),

 (55, "migrations-and-orms", "Databases III: migrations and ORMs",
  "SQLAlchemy 2.0 and Alembic",
  "sqlc generated queries and golang-migrate",
  "Raw SQL with a migration runner you write yourself",
  "You can evolve a schema safely in each language and say what an ORM buys and costs.",
  "ORM or raw SQL? Defend your answer."),

 (56, "redis-and-caching", "Caching with Redis",
  "redis-py: GET, SET, EX, and cache-aside",
  "go-redis: GET, SET, pipelines, and cache-aside",
  "redis-plus-plus: GET, SET, and cache-aside",
  "You can add a cache in front of a slow query in each language and measure the difference.",
  "How do you keep the cache and the database consistent?"),

 (57, "auth-hashing-jwt", "Authentication: hashing and tokens",
  "bcrypt/argon2, PyJWT, and a login flow",
  "bcrypt, golang-jwt, and a login flow",
  "Argon2 via libsodium, jwt-cpp, and a login flow",
  "You can store a password correctly and issue a signed token in each language.",
  "How do you store a password?"),

 (58, "testing-services", "Testing a service",
  "TestClient, fixtures for a test database, and mocking with respx",
  "httptest, table tests for handlers, and interfaces for mocking",
  "GoogleTest with an in-process server, and gMock",
  "You can test an HTTP handler in each language without a network or a real database.",
  "How do you test code that calls another service?"),

 (59, "docker", "Docker for each language",
  "A slim Python image with uv and a non-root user",
  "A multi-stage build to a scratch image",
  "A multi-stage CMake build to a distroless image",
  "You can containerise a service in each language and say why the images are 1 GB, 10 MB, and 20 MB.",
  "Why is your Docker image so large, and how would you shrink it?"),

 (60, "project-4-url-shortener", "Mini project 4: a URL shortener API",
  "FastAPI plus Postgres plus Redis",
  "net/http plus pgx plus go-redis",
  "cpp-httplib plus libpqxx plus redis-plus-plus",
  "You can build, test, containerise, and demo the same REST service in all three languages.",
  "Design and build a URL shortener. Now explain every choice."),

 # ---------------- 3b: Protocol Buffers and gRPC (61-75) ----------------
 (61, "what-protobuf-is", "Protocol Buffers: what and why",
  "JSON versus protobuf: size and speed, measured",
  "JSON versus protobuf: size and speed, measured",
  "JSON versus protobuf: size and speed, measured",
  "You can explain what a schema is, why binary beats text on the wire, and write your first .proto file.",
  "Why would you use protobuf instead of JSON?"),

 (62, "protoc-and-buf", "protoc, buf, and code generation",
  "Generating _pb2.py and using it",
  "protoc-gen-go, buf generate, and the generated .pb.go",
  "protoc --cpp_out and linking libprotobuf",
  "You can turn one .proto file into working code in all three languages with one command.",
  "What does the protobuf compiler generate, and why do you never edit it?"),

 (63, "messages-and-fields", "Messages: scalars, repeated, maps, nested, oneof",
  "Generated classes: repeated fields, map fields, and oneof in Python",
  "Generated structs: slices, maps, and the oneof interface pattern",
  "Generated classes: RepeatedField, Map, and oneof cases",
  "You can model an order with line items, an address, and a payment method that is one of three, in .proto.",
  "How do you express one-of-several in protobuf?"),

 (64, "field-numbers-and-evolution", "Field numbers, defaults, and schema evolution",
  "Reading old messages with a new schema in Python",
  "Reading old messages with a new schema in Go",
  "Reading old messages with a new schema in C++",
  "You can change a schema without breaking old clients, and name the four changes that will break them.",
  "Can you rename a field in protobuf? Can you change its type?"),

 (65, "well-known-types", "Well-known types",
  "Timestamp, Duration, Any, Empty, and wrappers from Python",
  "timestamppb, durationpb, anypb, and emptypb",
  "google/protobuf/timestamp.pb.h and friends",
  "You can represent time, absence, and a payload of unknown type in a message, in each language.",
  "How do you represent a time in protobuf?"),

 (66, "go-protobuf-api", "The Go protobuf API",
  "Python protobuf API: SerializeToString, ParseFromString, MessageToJson",
  "proto.Marshal, proto.Unmarshal, proto.Equal, protojson, and protoreflect",
  "SerializeToString, ParseFromString, and util::MessageToJsonString",
  "You can marshal, unmarshal, compare, and print messages, and say what the Go API does differently.",
  "How do you convert a protobuf message to JSON, and what gets lost?"),

 (67, "grpc-unary-server", "gRPC I: a unary server in Go",
  "grpcio: a Python server for the same service",
  "service in .proto, protoc-gen-go-grpc, and a Go server",
  "grpc++: a C++ server for the same service",
  "You can define a service in .proto and serve one RPC from Go, with Python and C++ servers as comparison.",
  "What is gRPC, and how is it different from REST?"),

 (68, "grpc-clients", "gRPC II: clients in three languages",
  "grpcio client with a channel and a stub",
  "grpc.NewClient, the generated client, and connection lifecycle",
  "grpc::CreateChannel and the generated Stub",
  "You can call the Go server from a Python client and a C++ client.",
  "How does a gRPC client find and talk to the server?"),

 (69, "grpc-streaming", "gRPC III: streaming",
  "Server streaming and bidirectional streaming from Python",
  "Server, client, and bidirectional streaming in Go",
  "Server and bidirectional streaming in C++",
  "You can stream a large result and a live feed over gRPC in each language.",
  "When would you use a streaming RPC instead of a unary one?"),

 (70, "grpc-errors-deadlines-metadata", "gRPC IV: errors, deadlines, metadata",
  "grpc.StatusCode, timeouts, and metadata in Python",
  "status.Error, codes, context deadlines, and metadata.MD",
  "grpc::Status, deadlines, and ClientContext metadata",
  "You can return a proper error with a code, propagate a deadline, and pass a request ID, in each language.",
  "How do errors work in gRPC?"),

 (71, "grpc-interceptors-auth-tls", "gRPC V: interceptors, auth, TLS",
  "Interceptors in grpcio and token auth",
  "Unary and stream interceptors, per-RPC credentials, TLS",
  "Interceptors in grpc++ and TLS credentials",
  "You can add logging and token auth to every RPC, and secure the connection, in each language.",
  "How do you authenticate a gRPC call?"),

 (72, "grpc-gateway-and-rest", "gRPC and REST together",
  "Calling a gRPC service from a FastAPI gateway",
  "grpc-gateway: JSON transcoding, and when to expose both",
  "Calling a gRPC service from a C++ HTTP handler",
  "You can expose one Go service as both gRPC and REST and say when to do that.",
  "Your mobile app cannot speak gRPC. What do you do?"),

 (73, "buf-lint-breaking-versioning", "Schema hygiene: lint, breaking checks, versioning",
  "Packaging generated Python code",
  "buf lint, buf breaking, module publishing, and package versioning",
  "Packaging generated C++ code with CMake",
  "You can enforce style and compatibility in CI and version an API like a professional team.",
  "How do you stop a teammate from shipping a breaking schema change?"),

 (74, "wire-format-by-hand", "The wire format, decoded by hand",
  "Dumping bytes and decoding them with the Python library",
  "protowire: reading tags and varints yourself",
  "Decoding a message with CodedInputStream",
  "You can look at 08 96 01 and say what field and what value it is.",
  "How is a protobuf message laid out in bytes?"),

 (75, "project-5-grpc-inventory", "Mini project 5: an inventory service over gRPC",
  "Python client and CLI",
  "Go server: protobuf API, Postgres, streaming stock updates",
  "C++ client and a load generator",
  "You can ship a Go gRPC service with schema, migrations, tests, and clients in the other two languages.",
  "Design a service API with protobuf. Now defend the field choices."),

 # ---------------- 3c: Performance and systems (76-90) ----------------
 (76, "benchmarking", "Benchmarking",
  "timeit, pytest-benchmark, and pyperf",
  "testing.B, b.N, benchstat, and allocation counts",
  "Google Benchmark and DoNotOptimize",
  "You can measure a function honestly in each language and say what makes a benchmark lie.",
  "How would you prove your change made it faster?"),

 (77, "cpu-profiling", "CPU profiling",
  "cProfile, py-spy, and flame graphs",
  "pprof CPU profiles and the flame graph",
  "perf, and flame graphs from a Release build with symbols",
  "You can find the hottest function in a real program in each language.",
  "Your service is slow. What do you run first?"),

 (78, "memory-profiling-and-leaks", "Memory profiling and leaks",
  "tracemalloc and objgraph",
  "pprof heap profiles, allocs, and GC traces",
  "AddressSanitizer, LeakSanitizer, and valgrind",
  "You can find what is holding memory in each language.",
  "Memory grows for an hour and then the process dies. Walk me through it."),

 (79, "cache-friendly-data", "Cache-friendly data layout",
  "Why lists of objects are slow, and arrays of numbers are fast",
  "Slices of structs versus slices of pointers, measured",
  "Struct of arrays, contiguous memory, and false sharing",
  "You can explain, with a measurement, why the same loop is ten times faster with a different layout.",
  "Why is iterating a linked list slower than iterating an array?"),

 (80, "numbers-precision-and-big", "Numbers: floats, decimals, and big integers",
  "float pitfalls, decimal, fractions, and arbitrary ints",
  "float64, math/big, and shopspring decimal",
  "double, long double, integer overflow, and a big-int library",
  "You can add money correctly and say why 0.1 + 0.2 is not 0.3, in each language.",
  "Why should you never store money as a float?"),

 (81, "binary-files-and-packing", "Binary data",
  "struct.pack, memoryview, and reading a binary header",
  "encoding/binary, byte order, and bytes.Buffer",
  "Byte order, std::bit_cast, and reading a binary header",
  "You can read and write a binary file format with a header in each language.",
  "What is endianness, and when does it bite?"),

 (82, "interop-ffi", "Calling across languages",
  "ctypes and pybind11: calling C++ from Python",
  "cgo: calling C from Go, and the cost of the boundary",
  "extern C, and exposing a C++ library to the other two",
  "You can write a hot loop in C++ and call it from Python and Go.",
  "When would you drop down to C++ from Python or Go?"),

 (83, "processes-and-signals", "Processes, subprocesses, and signals",
  "subprocess.run, Popen, pipes, and signal handling",
  "os/exec, pipes, and os/signal with graceful shutdown",
  "fork/exec, popen, and sigaction",
  "You can run another program, capture its output, and handle Ctrl-C cleanly, in each language.",
  "What happens when you press Ctrl-C on your server?"),

 (84, "filesystem-deep", "The filesystem",
  "pathlib, os.walk, tempfile, permissions, and watching for changes",
  "filepath.WalkDir, os.MkdirTemp, permissions, and fsnotify",
  "std::filesystem: walking, temp files, permissions",
  "You can walk a tree, write atomically, and react to changes in each language.",
  "How do you write a file so a crash never leaves it half-written?"),

 (85, "timers-and-scheduling", "Timers, tickers, and scheduling",
  "sched, asyncio.sleep, and a cron-like loop",
  "time.Ticker, time.AfterFunc, and a scheduler goroutine",
  "std::this_thread::sleep_until, and a timer wheel in outline",
  "You can run a job every minute, reliably, in each language, and say what drift is.",
  "How would you run a task every day at midnight inside a service?"),

 (86, "streams-and-large-data", "Streaming large data",
  "Generators, iterators over files, and chunked reads",
  "io.Reader, io.Writer, io.Pipe, and composing readers",
  "std::istream, iterators, and chunked reads",
  "You can process a 50 GB file with constant memory in each language.",
  "Why is io.Reader everywhere in Go?"),

 (87, "csv-yaml-toml", "Other data formats",
  "csv, tomllib, and PyYAML",
  "encoding/csv, BurntSushi/toml, and yaml.v3",
  "fast-cpp-csv-parser, toml++, and yaml-cpp",
  "You can read the three most common config and data formats in each language.",
  "YAML or TOML for config, and why?"),

 (88, "templates-and-codegen", "Templates and code generation",
  "Jinja2 for text, HTML, and generating code",
  "text/template, html/template, and go generate",
  "Generating C++ with a script, and CMake configure_file",
  "You can render a report from data and generate source code from a table, in each language.",
  "When is generating code better than writing it?"),

 (89, "plugins-and-dynamic-loading", "Plugins",
  "importlib, entry points, and a plugin registry",
  "Interfaces plus registration, and why the plugin package is avoided",
  "dlopen, shared libraries, and a C plugin ABI",
  "You can let someone add behaviour to your program without recompiling it, in each language.",
  "How would you let users extend your tool?"),

 (90, "project-6-log-pipeline", "Mini project 6: a log analytics pipeline",
  "Ingest, parse, and aggregate with generators and multiprocessing",
  "Ingest, parse, and aggregate with a channel pipeline",
  "Ingest, parse, and aggregate with a thread pool and mmap",
  "You can build the same pipeline in all three, benchmark them, and explain the numbers.",
  "Process 100 GB of logs and give me the top errors per hour. How?"),

 # ---------------- 3d: Messaging, resilience, deployment (91-105) ----------------
 (91, "kafka-producers-consumers", "Message brokers: Kafka",
  "confluent-kafka: produce, consume, commit",
  "franz-go: produce, consume, commit",
  "librdkafka: produce, consume, commit",
  "You can publish and consume events with a consumer group in each language.",
  "What is a message queue for?"),

 (92, "pubsub-patterns", "Pub/sub patterns",
  "Consumer groups, partitions, and ordering guarantees from Python",
  "Consumer groups, partitions, and ordering guarantees from Go",
  "Consumer groups, partitions, and ordering guarantees from C++",
  "You can explain at-least-once versus at-most-once and write an idempotent consumer in each language.",
  "What happens if your consumer crashes after processing but before committing?"),

 (93, "background-jobs", "Background jobs",
  "Celery or arq: enqueue, retry, and schedule",
  "asynq or a hand-built worker with Redis",
  "A worker process pulling from Redis lists",
  "You can move slow work out of the request path in each language.",
  "The email takes three seconds to send. Where does that code go?"),

 (94, "websockets", "WebSockets",
  "websockets and FastAPI WebSocket routes",
  "gorilla/websocket or nhooyr, and a broadcast hub",
  "Boost.Beast or uWebSockets, and a broadcast hub",
  "You can push live updates to a browser from each language.",
  "How does a WebSocket differ from HTTP?"),

 (95, "rate-limiting-and-retries", "Rate limiting and retries",
  "A token bucket, and tenacity for retries with backoff",
  "golang.org/x/time/rate, and retries with jitter",
  "A token bucket class, and retries with jitter",
  "You can protect a service from too many calls and retry safely, in each language.",
  "Why is retrying immediately worse than not retrying at all?"),

 (96, "circuit-breakers-and-idempotency", "Circuit breakers and idempotency keys",
  "A circuit breaker class and idempotency keys in a store",
  "gobreaker, and idempotency keys in a store",
  "A circuit breaker class and idempotency keys in a store",
  "You can stop cascading failure and make a payment endpoint safe to retry, in each language.",
  "A client retries a payment. How do you make sure it is charged once?"),

 (97, "metrics-and-tracing", "Observability: metrics and traces",
  "prometheus_client and OpenTelemetry",
  "prometheus/client_golang and OpenTelemetry",
  "prometheus-cpp and OpenTelemetry C++",
  "You can expose a metrics endpoint and a trace that crosses two services, in each language.",
  "What are the three pillars of observability?"),

 (98, "health-and-graceful-shutdown", "Health checks and graceful shutdown",
  "Liveness and readiness routes, and shutdown hooks",
  "Health endpoints, http.Server.Shutdown, and draining",
  "Health endpoints, stopping the server, and draining",
  "You can stop a service without dropping in-flight requests, in each language.",
  "What is the difference between liveness and readiness?"),

 (99, "config-secrets-flags", "Config, secrets, and feature flags",
  "Secrets from the environment, a vault client, and a flag store",
  "Secrets from the environment, a vault client, and a flag store",
  "Secrets from the environment, a vault client, and a flag store",
  "You can ship a feature dark and turn it on for 1% of users, in each language.",
  "How do you roll out a risky change safely?"),

 (100, "service-discovery-and-lb", "Service-to-service: discovery and load balancing",
  "gRPC client-side load balancing from Python",
  "gRPC resolvers, round-robin, and DNS-based discovery",
  "gRPC client-side load balancing from C++",
  "You can have three instances of a service and spread calls across them, from each language.",
  "How does a client find a healthy instance of a service?"),

 (101, "distributed-locks-and-election", "Distributed locks and leader election",
  "Redis locks and their limits",
  "etcd leases, leader election, and the lock lease trap",
  "Redis locks and their limits",
  "You can ensure only one instance runs the nightly job, and say why that is hard.",
  "How do you make sure only one instance runs a job?"),

 (102, "outbox-and-event-sourcing", "The outbox pattern and event sourcing",
  "Outbox table plus relay in Python",
  "Outbox table plus relay in Go",
  "Outbox table plus relay in C++",
  "You can publish an event and write to the database atomically, in each language.",
  "How do you write to Postgres and publish to Kafka without losing either?"),

 (103, "kubernetes-basics", "Kubernetes for your service",
  "Deployment, Service, probes, and resource limits",
  "Deployment, Service, probes, and resource limits",
  "Deployment, Service, probes, and resource limits",
  "You can run each of your three services on a local cluster with probes and limits.",
  "What does Kubernetes do when your pod dies?"),

 (104, "ci-pipelines", "CI for three languages",
  "GitHub Actions: uv, ruff, mypy, pytest, and coverage",
  "GitHub Actions: go vet, staticcheck, test -race, and coverage",
  "GitHub Actions: CMake, sanitizers, and ctest",
  "You can make every push run the tests for all three languages and block a bad merge.",
  "What runs when you open a pull request?"),

 (105, "project-7-orders-and-notifications", "Mini project 7: orders, events, and notifications",
  "Python notification worker consuming Kafka",
  "Go order service with gRPC, Postgres, and the outbox",
  "C++ pricing service called over gRPC",
  "You can ship three services that talk over gRPC and Kafka, with CI and health checks.",
  "Design an order pipeline with a notification step. Where can it lose a message?"),
]
